### DISCUSSION TITLE
Temperature Graph on VMs

### DISCUSSION THREAD

**Discussion by ameer1234567890** [henrygd/beszel#160] [Ideas]
Some of my beszel agents are installed on VMs and they are unable to provide temperature measurements, as expected.

I have mounted the temperature sensor device from within the VM and am able to read temperature data. I would like to provide this data to the beszel agent to consume. Is there any way?

**Comment by henrygd** [comment]
I'm assuming the VM is running Linux.

Temperatures are read from `/sys`. Do any of the commands below show files in your VM?

```bash
ls /sys/class/hwmon/hwmon*/temp*_input
ls /sys/class/hwmon/hwmon*/device/temp*_input
ls /sys/class/thermal/thermal_zone*/
```

**Reply by ameer1234567890** [reply]
VM is running debian.

Unfortunately, I am not able to mount anything in `/sys`. Instead I have mounted `/sys/class/thermal` from host to `/mnt/thermal/` on VM.

**Reply by henrygd** [reply]
Can you mount host `/sys` somewhere else? Like `/mnt/host_sys`?

If so, you can try setting an alternative location to `/sys` using the `HOST_SYS` environment variable.

**Reply by ameer1234567890** [reply]
I am not able to mount /sys into the VM, since I do not have root privileges in the host OS. But I can mount host's /sys/class/thermal into the VM.

**Reply by henrygd** [reply]
Seems like the only way to maintain compatibility with gopsutil would be to add an env var to override the sys location specifically for sensors.

You would need to mimic the sys path for your mount point, e.g., `/mnt/sys_sensors/class/thermal` (or hwmon), then provide `SYS_SENSORS=/mnt/sys_sensors`.

That way we should be able to use context to override the sys location specifically for [TemperaturesWithContext](https://github.com/shirou/gopsutil/blob/v4.24.8/sensors/sensors_linux.go#L22).

If that works then I can add it in a future release, but probably not the next one.

**Reply by ameer1234567890** [reply]
That would work. I could mount it to `/mnt/sys_sensors/class/thermal` and then provide `SYS_SENSORS` environment variable.

Appreciate if you would add this in a future release. Thanks.

**Comment by henrygd** [comment]
@ameer1234567890 I just added the `SYS_SENSORS` env var in 0.4.0. 

Haven't tested it with a VM so I didn't include it in the readme or release notes.

Try it out and let me know if it works for you, thanks.

**Comment by ameer1234567890** [comment]
I tried this but it didn't work. Here is my `compose.yml`

```
services:
  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:latest
    restart: unless-stopped
    network_mode: host
    environment:
      PORT: 45876
      KEY: ssh-ed25519 ------------------------------------------------------------------
      SYS_SENSORS: /mnt/sys/class/thermal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/mmc1/.beszel:/extra-filesystems/mmc1:ro
      - /mnt/sys/class/thermal:/mnt/sys/class/thermal
```

**Reply by henrygd** [reply]
Try the sys directory location instead of the subfolder:

```yml
services:
  beszel-agent:
    environment:
      SYS_SENSORS: /mnt/sys
    volumes:
      - /mnt/sys/class/thermal:/mnt/sys/class/thermal
```

**Reply by ameer1234567890** [reply]
Still didn't work.

Is it worth mentioning that the VM is hosted on an android device and `/sys/class/thermal` has exactly 100 sensors?

**Reply by henrygd** [reply]
That's awesome, first I've heard of anyone running it on an android device. Not sure why it would have 100 sensors though. Are there a lot of `thermal_zone` items?

I'll test `SYS_SENSORS` with vmware but may not be able to get around to it until the weekend.

**Reply by ameer1234567890** [reply]
Yes it has 100 `thermal_zone` items.

**Reply by henrygd** [reply]
Any chance the temps have started coming in on v0.5? I fixed an issue that might be related.

**Comment by ameer1234567890** [comment]
Yes it works. This is my setup.

1. I symlinked host's `/sys/class/thermal` on VM's `/mnt/sys/class/thermal`
2. I symlined host's `/sys/devices/virtual/thermal` on VM's `/mnt/sys/devices/virtual/thermal/`
3. My `docker-compose.yaml` is as below:
```
services:
  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:latest
    restart: unless-stopped
    network_mode: host
    environment:
      PORT: 45876
      KEY: ???????????????????????????????????
      SYS_SENSORS: /mnt/sys
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/sys:/mnt/sys
```
