### DISCUSSION TITLE
Help with inital setup/configuration. My system is always marked as "down"

### DISCUSSION THREAD

**Discussion by Kamikaze01git** [henrygd/beszel#193] [Support] [answered]
Hello.
I use a Synology DS920+ (Intel Celeron J4125) with DSM 7.2.1-69057 and Portainer Community Edition 2.19.4
I try to follow [mariushosting's explanation](https://mariushosting.com/how-to-install-beszel-on-your-synology-nas/) on how to deploy beszel on my Synology. But my system is always marked as "down".

I use volume2/dockers/ for my dockers, so my compose look like this:
```
services:
  beszel:
    container_name: Beszel
    image: henrygd/beszel:latest
    volumes:
      - /volume2/docker/beszel:/beszel_data:rw
    ports:
      - 8095:8090
    restart: on-failure:5

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: Beszel-Agent
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: #Your_Personal_Key
      FILESYSTEM: /dev/sda1
    restart: on-failure:5`
```

This works the way expected and in my LAN i can reach the docker with Port 8095 and create an admin account.
After that i try to add my system
```
Name: Synology
IP/HOST: 192.168.1.6
Port: 45876
Public Key: XXXXX
```

I copy the Public Key and paste it to the beszel-agent and update the docker.
Everything is okay, but my system (Synology) is always marked "down" in beszel.

This is the output from beszel docker:
```
2024/09/30 07:20:19 Server started at http://0.0.0.0:8090
├─ REST API: http://0.0.0.0:8090/api/
└─ Admin UI: http://0.0.0.0:8090/_/
```

This is the output from beszel-agent docker:
```
2024/09/30 07:32:21 WARN Partition details not found filesystem=/dev/sda1
2024/09/30 07:32:21 INFO Detected root device name=cachedev_0
2024/09/30 07:32:21 WARN Device not found in diskstats name=cachedev_0
2024/09/30 07:32:21 INFO Using I/O fallback name=md4
2024/09/30 07:32:21 INFO Detected network interface name=eth0 sent=314323649838 recv=1115989456495
2024/09/30 07:32:21 INFO Starting SSH server address=:45876
```
i also tried sda, sda0,  sda2, sda3, sda4 and sda5... or dab, sdb0, sdb1, sdb2,... but nothing changed.
System always shown as "down" :(

I am sure i do something wrong, but i can not find my mistake.
Pls help me to get these great dashboard for my synology server :)

Thank you !!!
