### DISCUSSION TITLE
Dex IdP configuration

### DISCUSSION THREAD

**Discussion by alex3305** [henrygd/beszel#22] [General]
I use [Dex](https://dexidp.io/) as my self hosted identity provider. This isn't a popular option AFAIK, but utilizing federation it is really easy for me to switch or implement multiple identity providers agnostic to the service or application. This also has the benefit that I only have to configure my external configuration (ie. Google, Github) once and at a single point, instead of configuring this on an application level.

I just want to show that Dex is compatible with the generic OIDC profile. A snippet from my Dex config:

```yaml
staticClients:
    # Dex internal ID is the Client ID for the service
  - id: beszel
    # This is the client secret, I usually use a random generated string
    secret: o8nZYKIpUTC50ZUqbAl8D6sgNHPL10Os
    name: 'Beszel'
    redirectURIs:
      - 'https://monitor.example.com/api/oauth2-redirect'
```
