### DISCUSSION TITLE
Use cloudflared to bypass firewall

### DISCUSSION THREAD

**Discussion by wwng2333** [henrygd/beszel#250] [General]
# After upgraded to v0.12, the agent can initiate the connection to the hub by adding HUB_URL and TOKEN to that agent. You may not need this at all.

Hi there, i found that we can use Cloudflare argo tunnel to easily bypass firewall, what we require is only setup a simple cloudflared on your hub and target machine. [Here](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/use-cases/ssh/ssh-cloudflared-authentication/) is the doc. It works fine, i already tested on beszel. I will show you how to do this step by step.
First, install cloudflared both on your target and the hub machine.
![image](https://github.com/user-attachments/assets/8613b19d-05f3-4afc-a26f-c495c6edf244)
Then add a ssh target like this, input your beszel client port, no special configure is required, everything is simple and easy.
![image](https://github.com/user-attachments/assets/69c0cc20-a23f-4cc6-a8b4-94212f437f9d)
Then start a cloudflared on you hub machine like this. You can also [setup config](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/local-management/configuration-file/) for daemon running.
```bash
root@crazy:~# cloudflared access ssh --hostname YOUR_HOSTNAME --url 127.0.0.1:22222
2024-11-03T13:47:34Z INF Start Websocket listener host=127.0.0.1:22222
```
Then we can add new system at beszel, very simple and easy.
![image](https://github.com/user-attachments/assets/1b629e21-bbca-463a-b06c-3b8c26d9aec3)

![image](https://github.com/user-attachments/assets/4b9578bc-4041-4f83-b434-0176d87f2368)
The only issue is the ip was shown as 127.0.0.1 :)

**Comment by henrygd** [comment]
Awesome, thanks for sharing!

We're in the process of converting the docs over to a standalone site. I'll make sure to mention this in that section.

**Reply by la3rence** [reply]
cloudflared may be not available in some specific Linux distributions. It would be helpful if beszel supports SSH Tunnel under the hood.

**Reply by wwng2333** [reply]
> cloudflared may be not available in some specific Linux distributions. It would be helpful if beszel supports SSH Tunnel under the hood.

It can running in docker. Here is the compose:
```yaml
services:
  beszel:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    ports:
      - '45876:45876'
    environment:
      PORT: 45876
      KEY: "YOUR_KEY"
  cloudflared:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=YOUR_TOKEN
```
