### DISCUSSION TITLE
Homepage widget error (ETIMEDOUT / valid admin authorization token)

### DISCUSSION THREAD

**Discussion by LDannijs** [henrygd/beszel#297] [Support] [answered]
Hello!

I am trying to get the homepage widget for beszel working (https://gethomepage.dev/widgets/services/beszel/) but i am getting an error.

![image](https://github.com/user-attachments/assets/98a297d3-0900-4db5-9a2c-83805c80f6bf)

Going to the URL shows me: 
```{"code":401,"message":"The request requires valid admin authorization token to be set.","data":{}}```

Here is how i have my service widget set up in homepage:

```
- Beszel:
      icon: sh-beszel-light.png
      href: http://192.168.1.75:8090/
      widget:
          type: beszel
          url: http://192.168.1.75:8090
          username: email
          password: password
          systemId: t082iox847jond2
```

**Comment by henrygd** [comment]
Hi, I didn't know this existed until now. That's neat. Thanks to whoever worked on this.

Looks like it's using the `/api/admins/auth-with-password` endpoint, so make sure you're using credentials for the admin account that you use to log into the PocketBase backend at `/_/#/login`.

**Reply by LDannijs** [reply]
Seems like it was @shamoon https://github.com/gethomepage/homepage/pull/4251

I only have a single user, and i checked the credentials i use to log into packetbase but theyre the same.

**Reply by henrygd** [reply]
Looks like your error code is `ETIMEDOUT`.

Make sure you can reach the Beszel host from inside your Homepage container (assuming you're using Docker).

```bash
docker exec -it homepage sh
```

```bash
ping 192.168.1.75
```

```bash
curl http://192.168.1.75:8090/api/admins/auth-with-password
```

**Reply by LDannijs** [reply]
```
user@machine:/home/docker/homepage$ docker exec -it homepage sh
/app # ping 192.168.1.75
PING 192.168.1.75 (192.168.1.75): 56 data bytes
64 bytes from 192.168.1.75: seq=0 ttl=64 time=0.081 ms
64 bytes from 192.168.1.75: seq=1 ttl=64 time=0.110 ms
64 bytes from 192.168.1.75: seq=2 ttl=64 time=0.102 ms
64 bytes from 192.168.1.75: seq=3 ttl=64 time=0.174 ms
64 bytes from 192.168.1.75: seq=4 ttl=64 time=0.098 ms
64 bytes from 192.168.1.75: seq=5 ttl=64 time=0.118 ms
64 bytes from 192.168.1.75: seq=6 ttl=64 time=0.093 ms
64 bytes from 192.168.1.75: seq=7 ttl=64 time=0.185 ms
64 bytes from 192.168.1.75: seq=8 ttl=64 time=0.103 ms
64 bytes from 192.168.1.75: seq=9 ttl=64 time=0.102 ms
64 bytes from 192.168.1.75: seq=10 ttl=64 time=0.115 ms
64 bytes from 192.168.1.75: seq=11 ttl=64 time=0.114 ms
^C
--- 192.168.1.75 ping statistics ---
12 packets transmitted, 12 packets received, 0% packet loss
round-trip min/avg/max = 0.081/0.116/0.185 ms

user@machine:/home/docker/homepage$ curl http://192.168.1.75:8090/api/admins/auth-with-password
{"code":401,"message":"The request requires valid admin authorization token to be set.","data":{}}
```

**Reply by henrygd** [reply]
Strange, I didn't expect that to work.

Are both containers on the same machine? If so, put them in a shared network and try using the Beszel `container_name` (probably `beszel`) as the host, instead of the LAN address.

**Reply by henrygd** [reply]
Also, it looks like you ran the `curl` command from your host. I can see the ping works, but did you also try running `curl http://192.168.1.75:8090/api/admins/auth-with-password` from within the container?

**Reply by LDannijs** [reply]
> Also, it looks like you ran the `curl` command from your host. I can see the ping works, but did you also try running `curl http://192.168.1.75:8090/api/admins/auth-with-password` from within the container?

I did but it gave me `sh: curl: not found`

**Reply by shamoon** [reply]
Ha, not sure if its intentional but you're basically walking through this: https://gethomepage.dev/troubleshooting/#service-widget-errors (which is why we have it =)

(step 3: "Note curl is not installed in the base image by default but can be added inside the container with apk add curl.")

**Reply by LDannijs** [reply]
Thanks for helping out @shamoon! I added curl with the `apk add curl` but when using the curl command the output remains empty. it doesn't return to the text field
![image](https://github.com/user-attachments/assets/afb60dbd-70fa-4757-bd58-a51e64207313)

**Reply by shamoon** [reply]
Indeed, it's presumably timing out. As henrygd mentioned, likely a networking thing: https://github.com/henrygd/beszel/discussions/297#discussioncomment-11328511

**Reply by LDannijs** [reply]
I am not *that* knowledgeable about docker. Do i just add a network in each compose file? Something like this:

```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    etc
  networks: 
    - beszel-homepage
```

```
services:
  beszel:
    image: 'henrygd/beszel'
    etc
  networks:
    - beszel-homepage
```

**Reply by shamoon** [reply]
There’s probably a good tutorial somewhere to google. But a lot of people will have a network that is shared between services that need to communicate (“backend” or whatever). So yea you add the containers to the shared network and then as Henry said you reference hosts by container_name and docker kind of magics the rest

**Reply by henrygd** [reply]
Pretty much. First create the network:

```bash
docker network create homepage_network
```

Then do what you showed, but also add a `services` block to identify the network:

```yml
services:
  homepage:
    networks:
      - homepage_network

networks:
  homepage_network:
    external: true
```

Do that for both files and bring them up again with `docker compose up -d`.

Then test connectivity again from the homepage container:

```bash
ping beszel
curl http://beszel:8090/api/admins/auth-with-password
```

**Reply by LDannijs** [reply]
Done all that, and it can ping it, but the curl still fails from inside the container: `{"code":401,"message":"The request requires valid admin authorization token to be set.","data":{}}`

Here are my compose files, might help you guys.

```
services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - '8090:8090'
    environment:
      - CSP=frame-ancestors http://192.168.1.75:8090 http://192.168.1.75:3000
    volumes:
      - ./beszel_data:/beszel_data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - homepage_network

  beszel-agent:
    image: 'henrygd/beszel-agent'
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: 'ssh-ed25519 key'

networks:
  homepage_network:
    external: true
```

```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - homepage_network

networks:
  homepage_network:
    external: true
```

**Reply by henrygd** [reply]
That's what you want!

The problem was that it couldn't connect at all before. Is the widget working in Homepage now by any chance?

**Reply by shamoon** [reply, marked as answer]
`{"code":401,"message":"The request requires valid admin authorization token to be set.","data":{}}` is expected since you're not actually passing the token, the curl was to test connectivity. It sounds like actually it is working now. The final thing is to change your homepage config to use that host, e.g.

```yaml
....
    widget:
        url: http://beszel:8090
```
