### DISCUSSION TITLE
Beszel without any authentication, auto-agent setup docker

### DISCUSSION THREAD

**Discussion by adamzvolanek** [henrygd/beszel#349] [Ideas]
Is it possible to setup a password-less Baszel instance (even without admin account) leveraging the `DISABLE_PASSWORD_AUTH` environment variable?

Likewise, is it possible to pre-populate the KEY the beszel-agent? I ask because to "simply" setup Baszel currently, I have to still interact with the Baszel dashboard not only to make an account but also setup the agent and re-create the beszel-agent `KEY`.

Current docker-compose file:

```yaml
services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    networks:
      - devrack
    ports:
      - '8090:8090'
    volumes:
      - /mnt/user/appdata/internal/beszel_data:/beszel_data
    environment:
      DISABLE_PASSWORD_AUTH: 'true'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  beszel-agent:
    image: 'henrygd/beszel-agent'
    container_name: 'beszel-agent'
    restart: unless-stopped
    networks:
      - devrack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: '...'

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true
```
