### DISCUSSION TITLE
Can't seem to load the dashboard behind reverse proxy

### DISCUSSION THREAD

**Discussion by tylovejoy** [henrygd/beszel#392] [Support]
Hey there,

If I expose the port, I can access the dashboard via VPS IP and port. But I use Caddy for my reverse proxy and when I configure Caddy, the page doesn't load.

Compose:
```
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    volumes:
      - ./beszel_data:/beszel_data
    networks:
      - network1
      - network2
      - network3

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # Do not remove quotes around the key
      KEY: 'UPDATE WITH YOUR PUBLIC KEY (copy from "Add system" dialog)'
    networks:
      - network1
      - network2
      - network3

networks:
  network1:
    external: true
  network2:
    external: true
  network3:
    external: true
```

Caddyfile:
```
*.example.com {
  tls {
    dns cloudflare {
      # Redacted
    }
  }
  @monitoring host monitoring.example.com
  handle @monitoring {
    reverse_proxy beszel:8090
  }
}
```

All of my other services work fine using this exact set up. Not sure what I could be missing? When going to monitoring.example.com I get a `Origin DNS error` Cloudflare page.
