### DISCUSSION TITLE
Guide to running inside of a Kubernetes cluster

### DISCUSSION THREAD

**Discussion by nodesocket** [henrygd/beszel#431] [General]
The following is a very rudimentary guide on how to run Beszel Hub and Beszel Agents inside of a Kubernetes cluster.

# Hub

Use a standard Kubernetes [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) and expose via a loadBalancer service or ingress. Nothing special is really needed for the hub.

# Agents

Use a Kubernetes [DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) (_deploys exactly one pod on every node automatically)_ and then add `tolerations` to allow deploying to the master/control-plane nodes. Finally, a few additional networking attributes are needed (`hostNetwork` and `ports`).

# Example Agent DaemonSet YAML

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: beszel-agent
  template:
    metadata:
      labels:
        app: beszel-agent
    spec:
      hostNetwork: true
      containers:
      - env:
        - name: PORT
          value: "45876"
        - name: KEY
          value: "YOUR-KEY-HERE"
        image: henrygd/beszel-agent:latest
        imagePullPolicy: Always
        name: beszel-agent
        ports:
          - containerPort: 45876
            hostPort: 45876
      restartPolicy: Always
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
```

# Adding Systems To Beszel

Since we are using `hostNetwork: true` you use the Kubernetes node IP address when adding the system. **Note: This is NOT the internal Kubernetes IP but the physical IP of the node itself.** Each Kubernetes node only runs a single agent pod thus why this works.

**Comment by henrygd** [comment]
Nice, thank you! This is super helpful. I'll probably link it somewhere in the docs.

**Comment by draeron** [comment]
do you know anyways to bridge the docker stats to the k8s apis when the runtime ain't docker (ie: k3s) ?

**Comment by nodesocket** [comment]
@draeron do you mean a way to monitor the containers runnings in each k8s node? I haven't got that working, but basically you'll need to expose the `containerd` socket.

The following may work, adjusting the Agent DaemonSet yaml:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: beszel-agent
  template:
    metadata:
      labels:
        app: beszel-agent
    spec:
      hostNetwork: true
      containers:
        - env:
            - name: PORT
              value: '45876'
            - name: KEY
              value: YOUR-KEY-HERE
          image: 'henrygd/beszel-agent:latest'
          imagePullPolicy: Always
          name: beszel-agent
          ports:
            - containerPort: 45876
              hostPort: 45876
          volumeMounts:
            - name: containerd-socket
              mountPath: /run/containerd/containerd.sock
              readOnly: true
      volumes:
        - name: containerd-socket
          hostPath: null
          path: /run/containerd/containerd.sock
          type: Socket
      restartPolicy: Always
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
```

Things to be aware of:

1.) Make sure your `containerd.sock` is at `/var/containerd`. I may also be located at `/var/run/containerd`.
2.) You may need to set `privileged: true`.

Let me know what you find!

**Comment by henrygd** [comment]
@draeron @nodesocket All container metrics come from `docker.sock` or `podman.sock`, unfortunately. We don't pull anything directly from containerd or cgroups. I'd like to experiment with that in the future, but for now it only works with Docker and Podman.

**Comment by draeron** [comment]
i guess one quick way would be to use some kind of containerd.sock -> docker.sock converter / bridge. Not sure if this exists

https://github.com/containerd/nerdctl/blob/main/pkg/statsutil/stats.go

**Comment by cfredericksen** [comment]
@nodesocket I deployed the hub and agent, in my on-prem kubernetes cluster, with your manifests and it worked great. I excluded the containerd stuff. Thank you.

**Reply by nodesocket** [reply]
Glad it worked.

**Comment by o10s** [comment]
@nodesocket how would you make beszel check Node disks ? Just mount the disk and that's it ?

**Comment by nodesocket** [comment]
@o10s not sure what you mean. Check Node disks? I get each Kubernetes Node disk usage right now.

**Reply by o10s** [reply]
@nodesocket if you run both agent and server on Kubernetes usually if you don't pass it a volume with let say /mnt/storage you wouldn't be able to receive it's stats cause the pod has no access to it right ? or am I missing something here ?

**Comment by SlavikCA** [comment]
I tried to use it with my k3s.

First issue:
```
2025/08/21 14:52:30 WARN Error creating WebSocket client err="HUB_URL environment variable not set"
2025/08/21 14:52:30 INFO Starting SSH server addr=:45876 network=tcp
2025/08/21 14:58:21 INFO Shutting down
2025/08/21 14:58:21 INFO Stopping SSH server
```

Added HUB_URL

Now getting:
```
2025/08/21 14:58:23 WARN Error creating WebSocket client err="must set TOKEN or TOKEN_FILE"
```

Added TOKEN (universal).
Now it started.

Also, there is no storage defined. Do I need storage for daemon?

Noted, that IP address for each system is the same (it actually the IP of my router, not the nodes):

<img width="1016" height="128" alt="Screenshot 2025-08-21 at 11 09 51" src="https://github.com/user-attachments/assets/e88c4132-fe06-45bd-8b00-61239fe2e6d8" />


<img width="1030" height="123" alt="Screenshot 2025-08-21 at 11 09 44" src="https://github.com/user-attachments/assets/1738a47a-bdc8-400a-8f79-1b4bb0291bd2" />

**Reply by henrygd** [reply]
This guide was written when agent clusters were more complicated to set up, prior to the introduction of the WebSocket connection and universal tokens.

The agent data directory is only used to store the system fingerprint, but may be used in the future for a SQLite database. The fingerprint is deterministic, so in most cases you can ignore warnings if no directory is found.

Regarding the agent IP, this can be changed by editing the system details in the table. Besides the display, this is only used for SSH connections if the WebSocket connection fails. We try to pull the real IP from `cf-connecting-ip` or `x-forwarded-for` headers:

https://github.com/henrygd/beszel/blob/7ba1f366ba822a9e97e9507e8ebd905455c06b96/beszel/internal/hub/agent_connect.go#L300-L320

**Reply by SlavikCA** [reply]
Thank you! I'm first time user, was reading docs...
And I think I just coming to understanding that there are 2 ways to connect hub and agent: SSH vs WebSocket.
I see it mentioned in https://beszel.dev/guide/security, probably deserve more prominent place in docs.

I'm still a bit confused about universal token. It said on the config page:
>  Expires after one hour or on hub restart.

And I can't find any info about universal token in the docs.

If it expires in an hour - does that means , that next time my Kubernetes node restarts (with agent pods) - it will not work and i'll need another token? If it creates "local" token based on universal token - where does it store it, if my container has no storage defined?

**Reply by henrygd** [reply]
The one hour window is specifically for new agent registration. Once registered, the token is set for the agent and does not change unless you manually rotate it. This is provided to the agent via env var so will always be static. It just allows the initial connection prior to the fingerprint being validated.

The fingerprint hash is based on unchanging system identifiers like `/etc/machine-id` or hardware, so it should generate the same value each time. If it does change and causes the agent to disconnect, this can be fixed by providing persistent storage for the agent and deleting the old fingerprint in the hub.

```yaml
volumes:
  - ./beszel_agent_data:/var/lib/beszel-agent
```

When I have time I'll make sure this is in the docs somewhere. Maybe an 'Architecture' or 'How it works' page.

**Comment by yair12** [comment]
Hi,

I wrote some containerd states addition leveraging current HUB docker representation.
This is mainly k8s flavored containers representation but it can potentially be generalized.
Need to be tested further but if anyone interested, we can incorporate this to beszel agent logic.

<img width="1864" height="959" alt="containerd_details" src="https://github.com/user-attachments/assets/0746c962-a349-47bf-ab44-87cdfb465a45" />



Example DaemonSet:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: beszel-agent
  template:
    metadata:
      labels:
        app: beszel-agent
    spec:
      hostNetwork: true
      hostPID: true  # Required so the agent can see host/container PIDs
      containers:
        - name: beszel-agent
          image: yairyotam/beszel-containerd-k8s:0.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: '45876'
            - name: KEY
              value: YOUR-KEY-HERE
            - name: CONTAINERD_ADDR
              value: /run/containerd/containerd.sock
          ports:
            - containerPort: 45876
              hostPort: 45876
          volumeMounts:
            - name: dbus
              mountPath: /var/run/dbus
              readOnly: true
            - name: var-log
              mountPath: /var/log
              readOnly: true
            - name: containerd-sock
              mountPath: /run/containerd/containerd.sock
      volumes:
        - name: dbus
          hostPath:
            path: /var/run/dbus
            type: Directory
        - name: var-log
          hostPath:
            path: /var/log
            type: Directory
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
            type: Socket
      restartPolicy: Always
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
```

Note: containerd.sock may be located elsewhere in different deployments.
