### DISCUSSION TITLE
DISABLE_PASSWORD_AUTH: true ?

### DISCUSSION THREAD

**Discussion by janreinhardt** [henrygd/beszel#453] [Support] [answered]
### Description

I would like to not login into Beszel. Disable authentication completely, because my homelab has got no open ports to the internet. It's purely internal.
So I've set `DISABLE_PASSWORD_AUTH: true` but it's not working out. Beszel ist still showing me a sign in page, with no fields to type in login data.
What am I missing?

![Screen Shot 2025-01-20 at 05 43 04 AM](https://github.com/user-attachments/assets/34b48b5e-fd08-4f57-ada3-d87ae89612de)

### OS / Architecture

latest Debian linux arm64 hub + agent

### Beszel version

0.9.1

### Installation method

Docker

### Configuration

```yaml
my docker-compose.yml:

    environment:
      DISABLE_PASSWORD_AUTH: true
```
