### DISCUSSION TITLE
Can't connect to same host agent with Docker Compose

### DISCUSSION THREAD

**Discussion by mauvehed** [henrygd/beszel#460] [Support]
### Description

First off, I've read through https://github.com/henrygd/beszel/issues/359 and tried many of the suggestions there. 

I just installed bezel and have no issues with the docker compose deployment on other hosts. However, nothing I do will enable the Hub to see my local agent. I've deployed via the example compose file:
```
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8090:8090
    volumes:
      - /data/docker/beszel/data:/beszel_data

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      # Do not remove quotes around the key
      KEY: "my key"
```

With this config I've tried host.docker.internal (as the docs suggest) and no go. The error in the logs is:
```
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

However, checking my /var/log files, I see no errors nor attempted SSH connections. I also know the key works and have tested it from multiple hosts.

I tried configuring a docker network and using the container name, that also didn't work.

Last thing, I have no firewall configured. ufw is disabled, but I still tried adding 45876 to iptables allow for both 127.0.0.1 and 0.0.0.0.

No go on anything.

### OS / Architecture

linux/amd64 (docker compose for hub & agent)

### Beszel version

0.9.1

### Installation method

Docker
