### DISCUSSION TITLE
docker portainer traefik - 404 page not found

### DISCUSSION THREAD

**Discussion by texonica** [henrygd/beszel#461] [Support]
### Description

i can't access the dashboard through / nor /_

### OS / Architecture

Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-51-generic x86_64) (hub)

### Beszel version

latest

### Installation method

Docker

### Configuration

```yaml
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8392:8090
    volumes:
      - ~/docker/volumes/beszel:/beszel_data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # API Router
      - "traefik.http.routers.beszel-api.rule=Host(`beszel.aaa.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.beszel-api.entrypoints=websecure"
      - "traefik.http.routers.beszel-api.tls=true"
      - "traefik.http.routers.beszel-api.tls.certresolver=letsencrypt"
      
      # Dashboard Router
      - "traefik.http.routers.beszel-dashboard.rule=Host(`beszel.aaa.com`) && PathPrefix(`/_`)"
      - "traefik.http.routers.beszel-dashboard.entrypoints=websecure"
      - "traefik.http.routers.beszel-dashboard.tls=true"
      - "traefik.http.routers.beszel-dashboard.tls.certresolver=letsencrypt"
      
      # Service
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```

### Hub Logs

```json
2025/01/20 17:15:50 Server started at http://0.0.0.0:8090

├─ REST API:  http://0.0.0.0:8090/api/

└─ Dashboard: http://0.0.0.0:8090/_/
```
