### DISCUSSION TITLE
Can't make it work on a Synology Nas with "Enable multiple gateways" activated in the Network options of the DSM

### DISCUSSION THREAD

**Discussion by josefhelie** [henrygd/beszel#547] [Support] [answered]
### Description

Hi,

First of all, thank you for your work and for this project! 🙏

Now, onto my issue: When I install Beszel, it works fine, but I need to enable the “Enable multiple gateways” option in DSM to VPN into my network using WireGuard from outside. However, as soon as I activate this option, Beszel loses connection with the agent.

I’m not a network expert, but this is the only way I’ve found to make remote access to my local network work.

With this option enabled, the agent does not get an IP address. I tried changing its network mode, which allows it to get an IP, but it still doesn’t work—the system is still reported as down.

What I’ve tested:
	•	Firewall off
	•	Both containers in bridge mode, host mode, and beszel_default
	•	Connecting to the server IP, Docker Agent IP and host.docker.internal server name

Could you help me resolve this issue?

### OS / Architecture

Synology DSM 7.2

### Beszel version

0.9.1

### Installation method

Docker

### Configuration

```yaml
services:
  beszel:
    container_name: Beszel
    image: henrygd/beszel:latest
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /volume2/docker/beszel:/beszel_data:rw
    ports:
      - 8090:8090
    restart: on-failure:5

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: Beszel-Agent
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: "ssh-ed25519 ###"
      FILESYSTEM: /dev/sda1
    restart: on-failure:5`
```

### Hub Logs

```
2025/02/10 16:43:39 Server started at http://0.0.0.0:8090

├─ REST API:  http://0.0.0.0:8090/api/

└─ Dashboard: http://0.0.0.0:8090/_/
```

### Agent Logs

```shell
2025/02/10 16:49:23 WARN Partition details not found filesystem=/dev/sda1
2025/02/10 16:49:23 INFO Detected root device name=dm-4
2025/02/10 16:49:23 INFO Docker 20.10.23 is outdated. Upgrade if possible. See https://github.com/henrygd/beszel/issues/58
2025/02/10 16:49:23 INFO Starting SSH server address=:45876
2025/02/10 16:51:22 WARN Partition details not found filesystem=/dev/sda1
2025/02/10 16:51:22 INFO Detected root device name=dm-4
2025/02/10 16:51:22 INFO Docker 20.10.23 is outdated. Upgrade if possible. See https://github.com/henrygd/beszel/issues/58

2025/02/10 16:51:22 INFO Starting SSH server address=:45876
```

**Comment by henrygd** [comment]
What happens if you run the containers in the same network and connect using the agent's container name (`Beszel-Agent`) as the hostname?

That should allow you to connect. If not try lowercase instead. You won't have network stats for the time being but I'm working on a way around that.

Also please let me know what the connection error is on the Logs page in PocketBase (`<your-url>/_/#/logs`).

```yml
services:
  beszel:
    container_name: Beszel
    image: henrygd/beszel:latest
    #extra_hosts:
    #  - host.docker.internal:host-gateway
    volumes:
      - /volume2/docker/beszel:/beszel_data:rw
    ports:
      - 8090:8090
    restart: on-failure:5

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: Beszel-Agent
    #network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: "ssh-ed25519 ###"
      FILESYSTEM: /dev/sda1
    restart: on-failure:5`
```
