### DISCUSSION TITLE
Ansible playbooks for install/uninstall inside

### DISCUSSION THREAD

**Discussion by hellofaduck** [henrygd/beszel#629] [General]
### Describe the feature you would like to see

I made ansible playbook for my k3s installations and want to share my solution if someone searching for this stuff.
Deleting role
```
- name: Remove beszel-agent if service exists
  block:
    - name: Populate service facts
      ansible.builtin.service_facts:
    
    - name: Download install-agent.sh script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-agent.sh
        dest: /tmp/install-agent.sh
        mode: '0755'  # Set executable permissions
      when: ansible_facts['services']['beszel-agent.service'] is defined
    
    - name: Remove beszel agent
      become: true
      ansible.builtin.command:
        cmd: /tmp/install-agent.sh -u
      when: ansible_facts['services']['beszel-agent.service'] is defined
```
Installation role with service existing check:
```
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Download the install-agent.sh script
  get_url:
    url: https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-agent.sh
    dest: /tmp/install-agent.sh
    mode: '0755'  # Set executable permissions
    
- name: Remove beszel agent if service exists
  become: true
  ansible.builtin.command:
    cmd: /tmp/install-agent.sh -u
  when: ansible_facts.services['beszel-agent.service'] is defined

- name: Run the install-agent.sh script
  shell: |
    if [ "{{ beszel_agent_autoupdate }}" = "true" ]; then 
      yes | /tmp/install-agent.sh -p {{ beszel_agent_ssh_port }} -k "{{ beszel_agent_ssh_key }}"
    else 
      yes N | /tmp/install-agent.sh -p {{ beszel_agent_ssh_port }} -k "{{ beszel_agent_ssh_key }}" 
    fi
  ignore_errors: false
```
You will also need to add these variables to your all.yml file:
```
# --= CUSTOM ADDONS =--
# Beszel monitoring ssh key for installing beszel agents on all nodes
beszel_agent: true
beszel_agent_autoupdate: true
beszel_agent_ssh_key: "ssh-ed25519 lalalal"
beszel_agent_ssh_port: 45876
```

### Describe how you would like to see this feature implemented

Its ready to use yaml

**Comment by henrygd** [comment]
Very nice, thanks!

At some point soon I'll add deployment examples for different software to the docs and include this for Ansible.

**Reply by henrygd** [reply]
Added: https://beszel.dev/guide/advanced-deployment

**Reply by hellofaduck** [reply]
I had some issues with the auto-update, so this is a fixed code for installation part

```yaml
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Download the install-agent.sh script
  get_url:
    url: https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-agent.sh
    dest: /tmp/install-agent.sh
    mode: '0755'  # Set executable permissions
    
- name: Remove beszel agent if service exists
  become: true
  ansible.builtin.command:
    cmd: /tmp/install-agent.sh -u
  when: ansible_facts.services['beszel-agent.service'] is defined

- name: Run the install-agent.sh script with auto-update
  shell: yes | /tmp/install-agent.sh -p {{ beszel_agent_ssh_port }} -k "{{ beszel_agent_ssh_key }}"
  when: beszel_agent_autoupdate | bool
  ignore_errors: false

- name: Run the install-agent.sh script without auto-update
  shell: yes N | /tmp/install-agent.sh -p {{ beszel_agent_ssh_port }} -k "{{ beszel_agent_ssh_key }}"
  when: not beszel_agent_autoupdate | bool
  ignore_errors: false
```

**Reply by henrygd** [reply]
Thank you! I updated the docs.

**Comment by JPCortesP** [comment]
Hello all, 
Pasting here my own playbook based on @hellofaduck, with a few modifications including in-file key and some checks. Tested on my 10+ hosts, including some which already had it installed and works fine for my needs. In case someone could use another example
```
---
# This playbook deploys the Beszel Agent on a target host.
# It ensures the required packages are installed, downloads the installation script,
# and runs the script to set up the Beszel Agent with specified SSH port and key.
# It also ensures the Beszel Agent service is running and enabled on boot.
- name: Deploy Beszel Agent
  hosts: all
  become: true
  vars:
    beszel_agent_ssh_port: 45876
    beszel_agent_ssh_key: "YOUR KEY HERE"
    beszel_agent_autoupdate: true
  tasks:
    - name: Check for Service Installed and Running
      ansible.builtin.stat:
        path: /etc/systemd/system/beszel-agent.service
      register: beszel_agent_service

    - name: Ensure the required packages are installed
      ansible.builtin.apt:
        name: curl
        state: present

    - name: Download the install-agent.sh script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-agent.sh
        dest: /tmp/install-agent.sh
        mode: '0755' # Set executable permissions


    - name: Run the install-agent.sh script with auto-update
      ansible.builtin.shell: |
        set -o pipefail
        yes | /tmp/install-agent.sh -p {{ beszel_agent_ssh_port }} -k "{{ beszel_agent_ssh_key }}"
      args:
        creates: /etc/systemd/system/beszel-agent.service
      when:
        - beszel_agent_autoupdate | bool
        - ansible_facts.services['beszel-agent.service'] is not defined or ansible_facts.services['beszel-agent.service'].state != 'running' or
          not beszel_agent_service.stat.exists
      ignore_errors: false

    - name: Ensure the beszel-agent service is running
      ansible.builtin.service:
        name: beszel-agent
        state: started
        enabled: true
      when: ansible_facts.services['beszel-agent.service'] is defined
```
