### DISCUSSION TITLE
How to check container health status for beszel-hub and beszel-agent?

### DISCUSSION THREAD

**Discussion by olegmeglin** [henrygd/beszel#649] [Support] [answered]
### Description

Hi,

first of all, thanks for your great work on this project! I really appreciate the effort put into beszel, and it's been a great tool to use.

I am using the official Docker images for **beszel-hub** and **beszel-agent** and was wondering if there is a recommended way to check the health status of these containers. I couldn’t find anything in the documentation or the Docker setup that defines a health check (e.g., via `HEALTHCHECK` in the Dockerfile or an API endpoint).  

### Questions

- Is there an existing method to monitor the health status of **beszel-hub** and **beszel-agent**?  
- If not, would adding a `HEALTHCHECK` in the Dockerfiles or an API status endpoint be a possible enhancement?  

### Example

Usually, I define a health check like this in my `docker-compose.yml`:  

```yml
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost"]
  interval: 1m30s
  timeout: 10s
  retries: 3
  start_period: 40s
  start_interval: 5s
```  

Depending on whether the container image includes `curl` or `wget`, the command could also be adjusted accordingly.  

### Why this matters

A defined health check would improve monitoring and allow for automated handling of issues (e.g., restarting the containers when necessary).

### OS / Architecture

linux/amd64 (agent)

### Beszel version

0.9.1

### Installation method

Docker
