### DISCUSSION TITLE
Local docker agent not connecting through unix socket

### DISCUSSION THREAD

**Discussion by Dav-Git** [henrygd/beszel#693] [Support] [answered]
### Description

Hi, I'm trying to set up beszel using docker compose and have been successful in connecting an external agent.
As instructed in the docs, I tried to set up a unix socket connection between the two containers (see attached docker-compose). However, the local system only shows as offline in the dashboard and the logs claim that the socket doesn't exist.
![image](https://github.com/user-attachments/assets/e7ce64e5-2e6b-4065-985a-785e49023734)
![image](https://github.com/user-attachments/assets/d0481d91-4b03-416a-b230-d1a49638a5fc)

By looking at my filesystem I can clearly see, that the socket does exist.
![image](https://github.com/user-attachments/assets/5b914cb5-ab07-44c5-a547-5a3c82e37689)

I'm pretty sure I'm missing something incredibly obvious, but do you have an idea as to why me setup is not working?
Thanks for the help in advance. 

### OS / Architecture

linux/amd64

### Beszel version

0.10.2

### Installation method

Docker

### Configuration

```yaml
services:
  beszel:
    image: henrygd/beszel:0.10.2
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8141:8090
    volumes:
      - /home/david/beszel/data:/beszel_data
      - /home/david/beszel/socket:/beszel_socket
    environment:
      DISABLE_PASSWORD_AUTH: 'true'

  beszel_agent:
    image: henrygd/beszel-agent:0.10.2
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/david/beszel/socket:/beszel_socket		# <-- This is where the socket should live
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/hdd2tb:/extra-filesystems/hdd2tb:ro		# Mount additional filesystems
      - /mnt/satassd:/extra-filesystems/satassd:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: 'ssh-ed25519 <some super secret key here>'
```

### Hub Logs

```json
{
  "id": "yjxw1eskzfajz7n",
  "created": "2025-03-18 13:10:35.479Z",
  "data": {
    "err": "dial unix /beszel_socket/beszel.sock : connect: no such file or directory",
    "system": "Frankie"
  },
  "message": "System down",
  "level": 8
}
```

### Agent Logs

```shell
N/A
```

**Comment by henrygd** [comment, marked as answer]
Hmm, not sure at first glance and wasn't able to replicate. Do you see this in the agent logs?

```
INFO Starting SSH server addr=/beszel_socket/beszel.sock network=unix
```

Maybe try pausing the system, then delete `/home/david/beszel/socket`, then recreate:

```bash
docker compose up -d --force-recreate --remove-orphans
``` 

Unpause the system and see if you get the same error. If so let me know what version of docker you're running.

**Reply by Dav-Git** [reply]
Hi, sorry for the super late reply and thank you for your answer :)

For whatever reason just doing a full re-setup worked.
I do have some more details on reproduction steps though, as I was able to replicate the issue (Docker: Docker version 28.0.1, build 068a01e)

1. Create the docker-compose as described in the getting started guide \
```YAML
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # Do not remove quotes around the key
      KEY: 'UPDATE WITH YOUR PUBLIC KEY (copy from "Add system" dialog)'
```
2. Click on add system in the Server UI. Follow all the steps until you're back on the dashboard.
3. Update the docker compose file with the public key from the UI, then recreate the agent container only
4. Pause and unpause the corresponding entry in the dashboard. No connection will be possible

I have a suspicion that the fact that I went through with the "Add System" wizard before adding the key in my docker compose might have caused the issue.
I have not investigated that (besides reproducing it once) further though.
