### DISCUSSION TITLE
How to Save the View Options?

### DISCUSSION THREAD

**Discussion by binggangu** [henrygd/beszel#695] [Support] [answered]
### Description

If I switch the Layout to Grid and hide some fields like GPU and Temp, it will only be saved to Local Storage. This means that if I clear the browser cache and log back in, the settings will go back to default. How can I resolve this?

### OS / Architecture

ubuntu

### Beszel version

0.10.2

### Installation method

Coolify

### Configuration

```yaml
services:
  beszel:
    image: 'henrygd/beszel:latest'
    container_name: beszel
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - './beszel_data:/beszel_data'
      - './beszel_socket:/beszel_socket'
  beszel-agent:
    image: 'henrygd/beszel-agent:latest'
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - './beszel_socket:/beszel_socket'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: 'ssh-ed25519 xxxx'
```
