### DISCUSSION TITLE
Wrong Time Zone?

### DISCUSSION THREAD

**Discussion by leadplasticmold** [henrygd/beszel#697] [Support]
### Description

Hello. I used the docker compose guide on the github, and everything is up and running. However, the logs don't seem to be reporting in my TZ which is America/New_York. Is there somewhere I can set this in the docker file?

### OS / Architecture

linux/amd64

### Beszel version

0.10.2

### Installation method

Docker

**Comment by henrygd** [comment]
Which logs? The direct container output or the logs in the PocketBase web UI?

**Comment by leadplasticmold** [comment]
My apologies, I meant in the web UI itself.

**Comment by leadplasticmold** [comment]
Hey just following up on this. I tried searching around and couldn't find an answer. My system time is US Eastern. I tried using TZ: America/New_York as an environment variable but that didnt seem to change anything. Where does it pull the timezone information from?

**Comment by AlienTFrost** [comment]
services:
  beszel:
    image: beszel:latest
    container_name: beszel
    environment:
      - TZ=America/New_York
    volumes:
      # give the container real zone files
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/localtime:/etc/localtime:ro

**Comment by oilervoss** [comment]
I found out Beszel doesn't care about the value of the usual TZ environment variable.
What bothered me was the docker/podman logs.
I could pass the host timezone mounting two relevant host folders:

```yaml
# to pass the host timezone from a Debian host to the container:
services:
  beszel-agent:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
```

`/etc/localtime` is a symbolic link to the timezone library located in `/usr/share/zoneinfo`. For this reason you need to mount both. If your host isn't Debian, you need to find out where your host timezone info is located. `ls -l /etc/localtime` may help.
