### DISCUSSION TITLE
Unable to login. "name" expected undefined.

### DISCUSSION THREAD

**Discussion by fabriciovergara** [henrygd/beszel#738] [Support]
### Description

Hi, 

I've self hosted beszel with it's agent in the same computer, but when I try to login it complains that a input name is "primary" and should be undefined.  In this case, "primary" is the name of my laptop.

I've tried to find documentation or look into the source code, but could not find a way to change the value set in the login form.  

When I add a break point right before the request is perfomed and change "primary" to "", then I can login successfuly.
Does anyone had this issue before or can guide me for a fix?

Thanks very much in advance.

<img width="1622" alt="Screenshot 2025-04-07 at 11 24 13" src="https://github.com/user-attachments/assets/6ef09d2e-a536-40aa-a14b-8ecf6f761b67" />

### OS / Architecture

linux/amd64 (hub/agent)

### Beszel version

v0.10.2

### Installation method

Coolify

### Configuration

```yaml
services:
  beszel:
    image: 'henrygd/beszel:latest'
    container_name: beszel
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - './beszel_data:/beszel_data'
      - './beszel_socket:/beszel_socket'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
  beszel-agent:
    image: 'henrygd/beszel-agent:latest'
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - './beszel_socket:/beszel_socket'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      - LISTEN=/beszel_socket/beszel.sock
      - 'KEY=${KEY}'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
```
