### DISCUSSION TITLE
Beszel Agent KO on SRV that runs Beszel

### DISCUSSION THREAD

**Discussion by seals187** [henrygd/beszel#762] [Support] [answered]
### Description

Hey Guys, 

I cant get the monitoring up an running for the agent on my VPS which hosts beszel. (monitor the SRV which runs beszel).
I've done it like explained here: https://beszel.dev/guide/getting-started (Start the hub); 
both docker containers are up and running, no FW problems. But its allways down.

Im running the containters, and apache2 as reverse proxy.
Am I missing something ? Or I did some mistakes ?

![image](https://github.com/user-attachments/assets/9d2af26c-3a17-4719-bf56-c483c8d31ca7)

best regards

### OS / Architecture

ubuntu 24.04

### Beszel version

0.10.2

### Installation method

Docker

### Configuration

```yaml
docker-compose:
---------------------

services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8080:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # Do not remove quotes around the key
      KEY: "xxx"


apache2:
---------------------

<VirtualHost *:443>
    ServerName xxx

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/xxx/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/xxx/privkey.pem

    ErrorLog ${APACHE_LOG_DIR}/xxx-error.log
    CustomLog ${APACHE_LOG_DIR}/xxx-access.log combined

    # Reverse proxy configuration for xxx
    ProxyPreserveHost On
    ProxyPass / http://localhost:8080/
    ProxyPassReverse / http://localhost:8080/

    # Add headers to inform the app it's behind HTTPS
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port "443"
</VirtualHost>
```
