### DISCUSSION TITLE
[HELP] Adding services from docker-compose

### DISCUSSION THREAD

**Discussion by volrod64** [henrygd/beszel#78] [Support] [answered]
Hello guys, 
If someone want to help a noob ..
I'm running all my services on a docker-compose.yml file 
https://privatebin.net/?ee73349a960bf611#3px6Wt4toPS299hGrhirGyZdcmmYSf57NCQSpyjcRQso

I added Beszel yesterday
running perfectly on http://ip:8090/
The problem is when I want to add a service with " Add system " .. I'm quite lost.
I put the IP and the port : nothing happened
I past something from my docker compose, like 
```
  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/prowlarr:/config 
```

Nothing happen. No error, just .. nothing. I'm stupid ? 

Begging for help rn lol

**Comment by henrygd** [comment, marked as answer]
No worries. You don't give beszel your docker information directly. You just need to run the agent, which gives the information to the hub automatically.

Here's an example docker-compose.yml for running both the hub and agent on the same machine. Then in the "add system" dialog you would enter a name like `localhost` and enter `host.docker.internal` as the host.

```yml
services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - ./beszel_data:/beszel_data
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  beszel-agent:
    image: 'henrygd/beszel-agent'
    container_name: 'beszel-agent'
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: '...'
      # FILESYSTEM: /dev/sda1 # set to the correct filesystem for disk I/O stats
```

**Reply by volrod64** [reply]
Is that litteraly what i'm suppose to do ?
```
services:

  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - /docker/appdata/beszel/data:/beszel_data
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  beszel-agent:
    image: 'henrygd/beszel-agent'
    container_name: 'beszel-agent'
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: '...'

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8088:8080

networks:
  default:
    driver: bridge
```

![image](https://github.com/user-attachments/assets/8debd770-85a5-4ab4-bc58-8b7c25159c56)

Sorry for those terrible questions ^^

**Comment by henrygd** [comment]
You need to replace "..." with your own key value that's displayed when you click 'Add System.'

I'm not sure why you edited my example to have "network_mode: bridge".

host.docker.internal is used specifically so you can run the agent in host mode. Otherwise you don't need to define any network mode. Just connect using the hostname or container_name value by putting that value in where it says "Host / IP" in 'Add System.'

See #73 for examples. You should delete the current localhost system and retry.

**Comment by volrod64** [comment]
```
services:

  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - /docker/appdata/beszel/data:/beszel_data
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  beszel-agent:
    image: 'henrygd/beszel-agent'
    container_name: 'beszel-agent'
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: 'my_key'
      
   
networks:
  default:
    driver: bridge
```

Worked ! Thanks for the help :)
