### DISCUSSION TITLE
see individual container stats/data?

### DISCUSSION THREAD

**Discussion by danktankk** [henrygd/beszel#782] [Support]
### Description

I know this is something that is doable because on my unraid server, beszel it will show individual docker containers, but I cant get that to work on any other host.  I have a few pi4's,  some VM's in proxmox, etc.  none of those list out and show container data.

I know it sees the containers because when I mouse over CPU or memory usage, it neatly lists out all containers it finds.  What am I missing here?  Sorry for any bother on this.  I did search as best I could - probably not using the correct key terms.  

### OS / Architecture

linux/amd64,arm64

### Beszel version

0.11.0

### Installation method

Docker

### Configuration

```yaml
beszel hub is in unraid and agents are preconfigured and look like:

services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszelAgent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      -/mnt/disk/.beszel:/extra-filesystems/sda2:ro
    environment:
      LISTEN: 45876
      KEY: "ssh-ed25519 <key>"
      LOG_LEVEL: debug
```

### Agent Logs

```shell
beszelAgent_pi4-1  | 2025/04/28 14:56:54 DEBUG Docker stats data="[0x4000308070 0x40000708c0 0x4000186cb0 0x40003083f0 0x4000308d90 0x4000070fc0 0x4000070c40 0x4000308a10 0x4000187570 0x4000186850 0x4000186bd0 0x40001872d0 0x40001873b0 0x4000187490 0x40001864d0]"
beszelAgent_pi4-1  | 2025/04/28 14:56:54 DEBUG Extra filesystems data="map[sda1:0x40001648c0 sda2:0x4000164850]"
beszelAgent_pi4-1  | 2025/04/28 14:57:54 DEBUG New session client=192.168.1.50:47896
beszelAgent_pi4-1  | 2025/04/28 14:57:54 DEBUG Temperature sensors="[{\"sensorKey\":\"cpu_thermal\",\"temperature\":41.381,\"sensorHigh\":0,\"sensorCritical\":0}]"
beszelAgent_pi4-1  | 2025/04/28 14:57:54 DEBUG sysinfo data="{Hostname:pi4-1 KernelVersion:6.12.20+rpt-rpi-v8 Cores:4 Threads:4 CpuModel:Cortex-A72 Uptime:2424116 Cpu:3 MemPct:27.37 DiskPct:0 Bandwidth:0 AgentVersion:0.11.0 Podman:false GpuPct:0 DashboardTemp:41.381 Os:0}"
beszelAgent_pi4-1  | 2025/04/28 14:57:54 DEBUG System stats data="&{Stats:{Cpu:3 MaxCpu:0 Mem:7.63 MemUsed:2.09 MemPct:27.37 MemBuffCache:5.38 MemZfsArc:0 Swap:0.2 SwapUsed:0 DiskTotal:0 DiskUsed:0 DiskPct:0 DiskReadPs:0 DiskWritePs:0 MaxDiskReadPs:0 MaxDiskWritePs:0 NetworkSent:0 NetworkRecv:0 MaxNetworkSent:0 MaxNetworkRecv:0 Temperatures:map[cpu_thermal:41.38] ExtraFs:map[] GPUData:map[]} Info:{Hostname:pi4-1 KernelVersion:6.12.20+rpt-rpi-v8 Cores:4 Threads:4 CpuModel:Cortex-A72 Uptime:2424116 Cpu:3 MemPct:27.37 DiskPct:0 Bandwidth:0 AgentVersion:0.11.0 Podman:false GpuPct:0 DashboardTemp:41.381 Os:0} Containers:[]}"
```
