### DISCUSSION TITLE
Custom name for disks? Or Alias?

### DISCUSSION THREAD

**Discussion by Robin-Croneld** [henrygd/beszel#819] [Support]
### Description

Hi!
When using additoonal disks on beszel-agent, is it possible to tell the agent to use a custom name for the disk?
Lets say i have a disk: /dev/sdd
The mounted folder: /mnt/archive

docker compose lines: 

`volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems

      - /mnt/archive/.beszel:/extra-filesystems/sdd:ro`

Is it possible to let beszel represent the folder-name instead of the device-name?

For some devices it can get confusing :)

### OS / Architecture

linux/amd64

### Beszel version

0.9.1

### Installation method

Docker

### Configuration

```yaml
services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      - /mnt/archive/.beszel:/extra-filesystems/sdd:ro

    environment:
      LISTEN: 45876
      KEY: "SECRET"
      LOG_LEVEL: debug
```
