### DISCUSSION TITLE
Error getting Docker memory stats in Alpine LXC

### DISCUSSION THREAD

**Discussion by vk2r** [henrygd/beszel#853] [Support]
### Description

I have installed the Beszel Agent in multiple containers; however, I'm having issues with my Alpine Linux containers. I use Proxmox to create LXC containers with Alpine Linux and Docker.

### Expected Behavior

I hope the error does not appear: "Error getting container stats err="beszel-agent - no memory stats - see https://github.com/henrygd/beszel/issues/144"

### Steps to Reproduce

1. Install Alpine Linux LXC in Proxmox
2. Install Docker with Docker Compose
3. Create docker-compose.yml with Beszel Agent

### OS / Architecture

Alpine Linux

### Beszel version

0.11.1

### Installation method

Docker

### Configuration

```yaml
services:
  mcpo:
    container_name: mcpo
    image: ghcr.io/alephpiece/mcpo
    ports:
      - 8000:8000
    volumes:
      - ./mcpo.json:/app/config.json
      - ./data:/mnt/data
    user: "${UID}:${GID}"
    
  mcp-hub:
    container_name: mcp-hub
    image: samanhappy/mcphub
    pull_policy: always
    volumes:
      - ./mcp.json:/app/mcp_settings.json
      - ~/obsidian:/mnt/obsidian
    ports:
      - 8030:3000
    restart: always
    env_file: .env
    user: "${UID}:${GID}"

  newt:
    image: fosrl/newt:latest
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=$PANGOLIN_ENDPOINT
      - NEWT_ID=$PANGOLIN_NEWT_ID
      - NEWT_SECRET=$PANGOLIN_NEWT_SECRET
    env_file: .env
    depends_on:
      - mcpo
      - mcp-hub
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: $BEZEL_PORT
      KEY: $BEZEL_KEY
    depends_on:
      - mcpo
      - mcp-hub
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  whatsupdocker:
    image: getwud/wud:latest
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - wud_store:/store
    env_file: .env
    depends_on:
      - mcpo
      - mcp-hub
    ports:
      - 3000:3000
    environment:
      - WUD_TRIGGER_DISCORD_MCPGATEWAY_URL=$WUD_DISCORD_URL
      - WUD_TRIGGER_DISCORD_MCPGATEWAY_BOTUSERNAME=$WUD_BOT_NAME
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  wud_store:
```

### Hub Logs

```json
ERROR Error getting container stats err="mcp-hub - no memory stats - see https://github.com/henrygd/beszel/issues/144
```

### Agent Logs

```shell

```
