### DISCUSSION TITLE
Empty Public key

### DISCUSSION THREAD

**Discussion by Lightjohn** [henrygd/beszel#869] [Support]
### Description

I followed docker-compose to create local Beszel server and agent.
I create admin account and when I try adding a new system public key is empty.
if I `cat beszel_data/id_ed25519.pub` in docker compose I have a key but even with that key given to the agent nothing will happen when trying to add local agent.

I just adapted docker-compose for my traefik / authelia setup

```
services:
  beszel:
    image: henrygd/beszel:latest
    restart: unless-stopped
    volumes:
      - "./beszel_data:/beszel_data"
      - "./beszel_socket:/beszel_socket"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monito.rule=Host(`url`)"
      - "traefik.http.routers.monito.middlewares=authelia@docker"
    networks:
      - traefik-net
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - "./beszel_socket:/beszel_socket"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      LISTEN: /beszel_socket/beszel.sock

      KEY: 'ssh-ed25519 key'

networks:
  traefik-net:
    name: traefik-net
```

![{3825C43A-5928-474B-825C-3F1AF4B71C09}](https://github.com/user-attachments/assets/62820287-0426-48ed-93c9-fc061c033789)
 

### OS / Architecture

debian 12

### Beszel version

latest

### Installation method

Docker

### Hub Logs

```json
beszel-1  |
beszel-1  | WARN You are using modernc.org/libc v1.64.0 which differs from the expected and tested v1.62.1.
beszel-1  | Please update your go.mod and manually set modernc.org/libc to v1.62.1, otherwise it could result in unexpected build or runtime errors (you may have to also run 'go clean -modcache' to clear the cache if the warning persists).
beszel-1  |
beszel-1  | 2025/06/07 17:06:56 Server started at http://0.0.0.0:8090
beszel-1  | ├─ REST API:  http://0.0.0.0:8090/api/
beszel-1  | └─ Dashboard: http://0.0.0.0:8090/_/
```
