### DISCUSSION TITLE
Disk Usage not showing in some cases

### DISCUSSION THREAD

**Discussion by ljhardy** [henrygd/beszel#880] [Support]
### Description

I have three Ubuntu 24.04 VMs set up identically, disk usage only shows for one.
![image](https://github.com/user-attachments/assets/d251dec0-8940-42a9-bcc4-65bdfc710085)

### OS / Architecture

Ubuntu 24.04 both hub and agent

### Beszel version

0.11.1

### Installation method

Docker

### Configuration

```yaml
services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/sda2/.beszel:/extra-filesystems/sda2:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: ssh-ed25519
        KEY HERE
networks: {}
```

### Hub Logs

WARN You are using modernc.org/libc v1.64.0 which differs from the expected and tested v1.62.1.
Please update your go.mod and manually set modernc.org/libc to v1.62.1, otherwise it could result in unexpected build or runtime errors (you may have to also run 'go clean -modcache' to clear the cache if the warning persists).
2025/06/09 17:05:22 Server started at http://0.0.0.0:8090
├─ REST API:  http://0.0.0.0:8090/api/
└─ Dashboard: http://0.0.0.0:8090/_/

### Agent Logs

2025/06/08 06:47:28 INFO Detected network interface name=enp6s18 sent=2280392 recv=265808
2025/06/08 06:47:29 INFO Starting SSH server addr=:45876 network=tcp
