### DISCUSSION TITLE
Issues with Discord Webhooks

### DISCUSSION THREAD

**Discussion by cobez83** [henrygd/beszel#910] [Support] [answered]
### Description

Hey all,
Just having issues where 

Error
sending message va service at "discord:// ID@TOKEN/title=TEST+ALERT "; failed to send discord notification: unexpected response status code: 400 Bad Reqest

### OS / Architecture

linux/amd64

### Beszel version

0.11.1

### Installation method

Docker

### Configuration

```yaml
beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8085:8090
    volumes:
      - /mnt/docker/beszel/beszel_data:/beszel_data
      - /mnt/docker/beszel/beszel_socket:/beszel_socket
```

### Hub Logs

```json
id	qarjja4eqsgjf8g
level	
ERROR (8)
created	2025-06-22 06:33:30.148 UTC
message	Error sending shoutrrr alert
data.err	locating service for URL "discord://X@X/?title=Test+Alert": discord: failed to initialize service

Removed token and ID (X)
```
