### DISCUSSION TITLE
Monitoring over Tailscale

### DISCUSSION THREAD

**Discussion by svenvg93** [henrygd/beszel#99] [Support]
Hi all! 

First of all I love this app, and thanks for all the work on it. 
As some of my systems are remote on other locations, I use tailscale to manage them. I installed the agent via docker on all of them. Now want to add them based on the tailscale name like `server01.tail495940.ts.net`. 
As the .tail495940.ts.net names are only resolvable via the tailscale dns, beszel hub running on the default docker bridge can't resolve them. 

I added the dns servers from tailscale magic dns to the container with 
```
dns: 
 - 100.100.100.100
 - 192.168.1.1
```

Not sure this the best way to do it, has anyone found a better way to monitor hosts over tailscale and local as well. As well as how can I `docker exec`  into the container to do some dns testing. bin, bash, sh don't work 😅

- Beszel Hub is running on docker with the default bridge network
- Beszel is running on docker 
- Tailscale is installed on the OS for all hosts

**Comment by crypt0rr** [comment]
I'm currently running Tailscale in a 'sidecar' configuration. So, for example, this is the configuration used for the hub.

```
---
version: "3.7"
services:
  tailscale-beszel-hub:
    image: tailscale/tailscale:latest
    container_name: tailscale-beszel-hub
    hostname: monitor
    environment:
      - TS_AUTHKEY=<YOUR-AUTH-KEY>
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=false
    volumes:
      - /home/docker-user/beszel/config:/config
      - /home/docker-user/beszel/tailscale-beszel-hub/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  beszel-hub:
    image: 'henrygd/beszel'
    network_mode: service:tailscale-beszel-hub
    container_name: beszel-hub
    restart: unless-stopped
    volumes:
      - /home/docker-user/beszel/hub/beszel_data:/beszel_data
```

In the above configuration I expose the Beszel hub to my Tailnet with `tailscale serve` this is done with the variable `TS_SERVE_CONFIG` which contains the following content:

```
{
    "TCP": {
      "443": {
        "HTTPS": true
      }
    },
    "Web": {
      "${TS_CERT_DOMAIN}:443": {
        "Handlers": {
          "/": {
            "Proxy": "http://127.0.0.1:80"
          }
        }
      }
    }
  }
```

I'm running the agent in it's own container. The host where the containers 'live' on, is also connected to Tailscale. Following is the container running the agent.

```
---
version: "3.7"
services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: "<YOUR-SSH-KEY>"
      # FILESYSTEM: /dev/sda1 # set to the correct filesystem for disk I/O stats
```

The hub points to the Tailscale IP address of the docker host.

For reference:
- [Get started with Docker and Tailscale - by Tailscale](https://www.youtube.com/watch?v=YTjYXii4WzI&t=3s)
- [A deep dive into using Tailscale with Docker - by Tailscale](https://www.youtube.com/watch?v=tqvvZhGrciQ)

**Reply by svenvg93** [reply]
I thought about that as well. Does it not limit the hub to be only accessible via the tailnet? I still want to be able to access it local when im home without the need to use tailscale.

**Reply by crypt0rr** [reply]
Yes, to fix this you can add the `ports` exposure to the TS config. For example, like this:

```
services:
  tailscale-beszel-hub:
    image: tailscale/tailscale:latest
    container_name: tailscale-beszel-hub
    hostname: monitor
    ports:
      - 8090:8090
....
```
