### ISSUE TITLE
FILESYSTEM env var for Rpi4

### ISSUE THREAD

**Issue by GeorgeG92** [henrygd/beszel#138]
For the life of me, I cannot find which path I should use for the FILESYSTEM variable on my raspberry pi4 (with sd card), thus having 0 values in my Disk IO charts. I have tried all 3 commands noted in the readme file and used all paths that I got from there. Any advice?

**Comment by henrygd** [comment]
Please share the relevant output of `df -h` and your configuration (docker-compose or unit file or command).

I've not tested with sd cards but I don't think it would be any different.

**Comment by GeorgeG92** [comment]
Alright, so my docker-compose file is:

```

version: "3.9"
services:
  beszel:
    container_name: Beszel
    image: henrygd/beszel:latest
    volumes:
      - /path/to/beszel:/beszel_data:rw
    ports:
      - 8095:8090
    restart: always

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: Beszel-Agent
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: MYSSHKEY
      FILESYSTEM: /dev/root
    restart: always
```

The output of df -h is:
```

Filesystem      Size  Used Avail Use% Mounted on
/dev/root       118G   27G   86G  24% /
devtmpfs        1.7G     0  1.7G   0% /dev
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           759M  2.3M  757M   1% /run
tmpfs           5.0M   16K  5.0M   1% /run/lock
/dev/mmcblk0p1  255M   31M  225M  13% /boot
tmpfs           380M   24K  380M   1% /run/user/1000

```
