### ISSUE TITLE
Authelia OIDC

### ISSUE THREAD

**Issue by Heavensong89** [henrygd/beszel#15]
Tried to setup Authelia, I've tried using oidc, oidc2, oidc3, and all of them with "Support PKCE" either checked or unchecked - no joy! When I click the Authelia buttons on the login page, I just get a blank pop-window. This is my authelia config, wondering if I've missed anything:

```      ## Beszel
      - client_id: 'beszel'
        client_name: 'Beszel'
        client_secret: {{ secret "/secrets/oidc/beszel" }}
        pre_configured_consent_duration: '7d'
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://beszel.example.net/api/oauth2-redirect'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'

**Comment by MFYDev** [comment]
I am using Authentik and have no issues at all. Although Authentik and Authelia are different but the basic setting should be similar. The info you provided is not enough for me to help.

**Comment by Heavensong89** [comment]
![Screenshot 2024-07-25 215735](https://github.com/user-attachments/assets/839eb256-d03f-4c06-8482-9d720483b544)

That's how I've got it setup in beszel, and then my original message is the Authelia config that goes in the yaml file

**Comment by MFYDev** [comment]
`'https://beszel.example.net/api/oauth2-redirect'`

Did you set it as your own beszel instance? or just as the `example.net` you pasted?

**Comment by Heavensong89** [comment]
my own instance

**Comment by MFYDev** [comment]
https://www.authelia.com/integration/openid-connect/pocketbase/

I found a related documentation from Authelia official website. Could you please confirm your setting again by following this? Beszel backend is pocketbase. This doc should be able to guide you through everything

**Comment by Heavensong89** [comment]
yes it matches this, I added in the additional userinfo_signed_response_alg option and it still isn't working - I don't think it's hitting Authelia at all, as there are no errors/warning in my authelia logs. And I just get a blank pop-up window when I click the button, I don't get an error message.

```      ## Beszel
      - client_id: 'redacted'
        client_name: 'Beszel'
        client_secret: {{ secret "/secrets/oidc/beszel" }}
        pre_configured_consent_duration: '7d'
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://beszel.redacted.net/api/oauth2-redirect'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
        userinfo_signed_response_alg: 'none'

**Comment by henrygd** [comment]
Do you see any related errors in the PocketBase logs? `<your-url>/_/#/logs`

**Comment by Heavensong89** [comment]
![Screenshot 2024-07-25 223826](https://github.com/user-attachments/assets/dfcd1ea1-341d-4e08-9bee-454b00b4e405)
no errors in the log

**Comment by henrygd** [comment]
Not sure what to suggest here. OIDC is handled by PocketBase and other providers like Authentik and Zitadel are confirmed to be working in Beszel. Maybe someone else who uses Authelia OIDC will see this and have a solution.

I'll add it to my list to investigate but it's not top priority at the moment. Until it gets sorted out I'd recommend using a different auth method or just putting the Authelia portal in front of the whole application.

**Comment by peterbuga** [comment]
I use authelia just fine, here's my config:
```
      - client_id: 'beszel-client'
        client_name: 'Beszel OpenID Client'
        client_secret: 'SECRET'
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://beszel.EXAMPLE.COMh/api/oauth2-redirect'
        scopes:
          - 'email'
          - 'groups'
          - 'openid'
          - 'profile'
        userinfo_signed_response_alg: 'none'
```

followed the tutorial from here: https://www.authelia.com/integration/openid-connect/pocketbase/
