### ISSUE TITLE
Copy docker compose with no formatted yaml

### ISSUE THREAD

**Issue by bergpb** [henrygd/beszel#152]
Hi, first thanks for creating this project.
When I create a new system and need to copy the compose file, it copies with unformatted yaml:

`services:  beszel-agent:    image: "henrygd/beszel-agent"    container_name: "beszel-agent"    restart: unless-stopped    network_mode: host    volumes:      - /var/run/docker.sock:/var/run/docker.sock:ro    environment:      PORT: 45876      KEY: "ssh-ed25519 ..."      # FILESYSTEM: /dev/sda1 # set to the correct filesystem for disk I/O stats`

So I need to format it before adding it to the compose file.
Will be great if we could copy and paste the code with the yaml code already ready to be pasted to a compose file:

```
services: 
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:      
      PORT: 45876      
      KEY: "ssh-ed25519 ..."
      # FILESYSTEM: /dev/sda1 # set to the correct filesystem for disk I/O stats`
```

Beszel version: v0.2.0
Browser: Firefox 129.0.2
