### ISSUE TITLE
Beszel agent not detecting docker

### ISSUE THREAD

**Issue by steveiliop56** [henrygd/beszel#166]
Hello,

I installed the beszel agent on my 2 docker hosts using this docker compose file:

```yaml
version: '3.9'
services:
  beszel-agent:
    image: henrygd/beszel-agent:0.3.0
    container_name: beszel-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: somekey
      FILESYSTEM: somefs
```

The first docker host is running debian server and the second one raspberry pi os. The beszel server is running on raspberry pi os. For some reason I only get the docker stats for the debian server one and not for my raspberry pi. I tried restarting and stuff but no luck. Any ideas?
