### ISSUE TITLE
No Disk I/O charts

### ISSUE THREAD

**Issue by Pootch** [henrygd/beszel#183]
Can somebody help with the disk i/o chart. It does not show any stats.

My docker compose:

```
services:
  beszel:
    container_name: Beszel
    image: henrygd/beszel:latest
    volumes:
      - /volume1/docker/beszel:/beszel_data:rw
    ports:
      - 8095:8090
    restart: on-failure:5

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: Beszel-Agent
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: mykey
      FILESYSTEM: /dev/vg1/volume_1
    restart: on-failure:5
```
