### ISSUE TITLE
agent ssh server starts on ipv6

### ISSUE THREAD

**Issue by MarkusGnigler** [henrygd/beszel#232]
i have a docker deployment of the agent in a regular ipv4 network and the ssh server starts only on ipv6.
i does not have anything configure for ipv6 and i have set the the `PORT` variable to `0.0.0.0:45876`

```bash
╰─λ netstat -tulpn | grep 45876
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::45876                :::*                    LISTEN      -
```

This obviously means i cant reach my agent.

```bash
╰─λ telnet 10.0.0.15 45876
Trying 10.0.0.15...
telnet: connect to address 10.0.0.15: No route to host
```

Is it somewhat related to the start process?

https://github.com/henrygd/beszel/blob/ec7cb53d935b7d07ed1fbf8fd0893856e75c3981/beszel/internal/agent/server.go#L15

**Comment by henrygd** [comment]
Maybe try `10.0.0.15:45876`, or just `45876`.

If that doesn't work, please paste your docker compose here.

**Comment by MarkusGnigler** [comment]
Thanks for the fast reply.

I have started with the `PORT` variable set only to 45876 as from the example docker compose file.

Kind of fixed it for now by removing the `network_mode: host` and using regular port mapping.

This is my docker compose file:

```yml
services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    ports:
      - 45876:45876
#    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk1/.beszel:/extra-filesystems/disk1:ro
    environment:
      PORT: 0.0.0.0:45876
      KEY: "XXX"
      # FILESYSTEM: /dev/sda1 # override the root partition /

```

Any guess whats the problem here? Network monitoring would be nice.
