### ISSUE TITLE
eMMC

### ISSUE THREAD

**Issue by Eirikr70** [henrygd/beszel#240]
Hello,
My root disk is an eMMC. As is, Beszel doesn't show its space and I/O (permanently at 0). I suppose Beszel is not capable of gathering the info for the eMMC technology ?...

**Comment by HyperrJedi** [comment]
I have emmc storage on one of my devices and I set the file system to /dev/mmcblk1p2 and it works perfectly.

**Comment by Eirikr70** [comment]
Right, so I guess I have a problem with my config. Can you check it ?
```
services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    environment:
      TZ: "Europe/Paris"
    ports:
      - '8099:8090'
    volumes:
      - /srv/nas/beszel:/beszel_data
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      - /srv/nas/.beszel:/extra-filesystems/nas:ro
      - /srv/backup/.beszel:/extra-filesystems/backup:ro
#       - ./.beszel:/extra-filesystems/mmcblk0p2:ro
    environment:
      TZ: "Europe/Paris"
      PORT: 45876
      KEY: "ssh-ed..."
      FILESYSTEM: /dev/mmcblk0p2 # override the root partition / device for disk I/O stats
```

**Comment by HyperrJedi** [comment]
This is what I have
```
server@server:~$ lsblk
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
loop0          7:0    0 73.9M  1 loop /snap/core22/1663
loop1          7:1    0 10.7M  1 loop /snap/canonical-livepatch/286
loop2          7:2    0 38.8M  1 loop /snap/snapd/21759
mmcblk0      179:0    0 57.6G  0 disk
├─mmcblk0p1  179:1    0    1G  0 part /boot/efi
└─mmcblk0p2  179:2    0 56.6G  0 part /
mmcblk0boot0 179:8    0    4M  1 disk
mmcblk0boot1 179:16   0    4M  1 disk
```

This is the agent

```
beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: ssh-ed25519....

      FILESYSTEM: /dev/mmcblk1p2
```

Maybe instead of using /dev/mmcblk0p2 try /dev/mmcblk1p2? Thats all i got
