### ISSUE TITLE
Hub programmatic configuration?

### ISSUE THREAD

**Issue by giorgiga** [henrygd/beszel#275]
I am packaging for beszel for NixOs, because I want to use it in my home lab and I guess others too may want to (I do plan contribute my efforts to the official repo once I'm satisfied). 

At the moment, I have packaged both the agent and hub and I'm working on the agent's *module* (you may think of it as an elaborate installation script).

Since things are going well with the agent (I think I'll be done this weekend or the next one), so I took a preliminary look at the hub, but it seems the hub is intended to be configured interactively by a person, while the "nixos way" would be for the nixos module to generate all the needed configuration so that one can materialize a working system.

Is it possible to programmatically configure the hub beyond the two environment variables mentioned in the README?

**Comment by henrygd** [comment]
Cool! Thanks for doing that. I think there's also some work being done for nixpgs here: https://github.com/NixOS/nixpkgs/pull/345444

Systems can be defined programmatically in `beszel_data/config.yml`:

```yaml
# Values for port and users are optional.
# Defaults are port 45876 and the first created user.

systems:
    - name: thinkpad
      host: 192.168.33.5
      port: 45876
      users:
        - name@example.com
```

But creation of the first user is done in the application. What would be the ideal "nixos way" to do this?
