### ISSUE TITLE
NVME disks

### ISSUE THREAD

**Issue by durandguru** [henrygd/beszel#294]
Hi,

I have 4 nvme disks on my ubuntu 24.04 server. After every reboot the nvme disks have another identifier. So /dev/nvme1n1p1  can be /dev/nvme0n1p1 .

For the disk which hosts the / mount everything works fine. But the 3 data diks have every reboot another ID (apparently an known issue in ubuntu).

In Beszel the graphs are coupled to the name of the disk, so after a reboot the graphs kinda work after an time but history is wrong. My mounts are mapped by uuid.

Is there an soulution for this?

Filesystem                         Size  Used Avail Use% Mounted on
/dev/mapper/ubuntu--vg-ubuntu--lv  914G   33G  843G   4% /
/dev/nvme1n1p1                     916G  633G  237G  73% /mnt/media
/dev/nvme2n1p1                     916G  108G  763G  13% /mnt/files
/dev/nvme3n1p1                     1.8T  1.2T  605G  66% /mnt/photos
/dev/nvme0n1p2                     2.0G   96M  1.7G   6% /boot
/dev/nvme0n1p1                     1.1G  6.2M  1.1G   1% /boot/efi

**Comment by henrygd** [comment]
Good point, I hadn't considered that.

We can use the UUID, but it would not be ideal to display something like `e858d363-aaa8-4a5e-9da1-fbe0ef63af1b Usage` as the chart title.

Maybe we can use the label as the identifier if it's defined?

```
lsblk -o NAME,LABEL,MOUNTPOINT
```

**Comment by durandguru** [comment]
Labels won't stick for now on 2 drives. I will troubleshoot...

Or use the name for docker in the volume after extra-filesystems?
volumes:
  - /mnt/disk1/.beszel:/extra-filesystems/sdb1:ro

NAME                      LABEL MOUNTPOINT
nvme3n1
└─nvme3n1p1                     /mnt/photos
nvme2n1
└─nvme2n1p1               files /mnt/files
nvme1n1
└─nvme1n1p1                     /mnt/media
nvme0n1
├─nvme0n1p1                     /boot/efi
├─nvme0n1p2                     /boot
└─nvme0n1p3
  └─ubuntu--vg-ubuntu--lv       /

**Comment by durandguru** [comment]
Btw, with extra disks the title and explanation is displayed. I get why it is there but it kind off says the same :-)

nvme1n1p1 Usage
Disk usage of nvme1n1p1

![Schermafbeelding 2024-11-19 om 22 09 53](https://github.com/user-attachments/assets/0fb2326f-6420-4ab2-bb96-45a15eb08b45)

**Comment by henrygd** [comment]
Copy/pasting my comment from #350:

I think the best option is to use label values straight from the disk if available. Maybe add a manual env var mapping if you don't want to use disk labels for whatever reason.

If you have time, can you run the agent with `LOG_LEVEL=debug` and check the line containing `DEBUG Disk I/O diskstats` that's logged on startup?

It should show info for your disks including labels. I just want to make sure those label values come through properly.

**Comment by codingmatty** [comment]
I just ran the agent with debug logs and it looks like the label is empty for all of my drives, whereas the `lsblk` command above is showing the correct labels on the disks. Is this expected?

**Comment by henrygd** [comment]
@codingmatty Thank you, fellow Chattanoogan. Small world. Looks like labels are not coming through on the Docker agent. I'll investigate further.

**Comment by 4JX** [comment]
Hey, any updates on this? My issue is pretty similar. I mainly have two drives that like to interchange between `sda` and `sdb` on reboot.

That part is mostly remediated by using the mount location, but I also need to apply the "specify where to read IO" bit, which means I need to [reference](https://github.com/4JX/nixos-config/commit/5abd3e3ea580dc65d04e9f6b06e6d336f8d2b760#diff-bfa469da2d04fcf821e4b466f891678935df0ca66bd50654d4070997f4ecc77dR21-R25) `sda` and `sdb`, and (have yet to test it) that will probably mess the stats up due to the disconnect between the drives and the `sd#` entries.

Edit: It did, in fact, not survive a reboot. The stats for the IO of the mounts have indeed swapped.

**Comment by nfgrep** [comment]
Would also love to see something more stable here. Disk labels might be nice aswell. 
e.g. `/mnt/SOMEDISKLABEL:/extra-filesystems/SOMEDISKLABEL:ro`, would remove (atleast my) requirement to add a `__SomeName` thing in addition to the actual disk identifier.

**Comment by nodesocket** [comment]
Adding my previous issue comment here as well:

Component
Agent

Description
Apparently device names `/dev/sd*` can change depending on:

Linux assigns `/dev/sdX` names dynamically at boot time based on detection order. That order can change because of:

- Disk initialization timing (one drive spins up faster)
- Controller / BIOS behavior
- SATA port scan order
- USB or RAID controllers appearing earlier/later
- Kernel updates or driver differences

So:

Boot 1 → root disk detected first → /dev/sda1
Boot 2 → docker data disk detected first → /dev/sdb1

Result: they swap names, even though they’re the same physical disks.

This breaks my configuration of:

```
/extra-filesystems/sdb1__docker => /var/lib/docker
/extra-filesystems/sda1__root => /
```

It's not deterministic. The general consensus seems to be using UUIDs instead of `/dev/sd*` paths.

This also affects the envar `FILESYSTEM` as `/dev/sda1` can change upon reboot.

Motivation / Use Case
Nondeterministic disk names.

**Comment by Haorran** [comment]
<img width="1628" height="732" alt="Image" src="https://github.com/user-attachments/assets/d2272d4a-2814-4f80-99c9-0a70123756de" />

不知道为什么，现在显示交叉了
......
      - /vol2/.beszel:/extra-filesystems/sda1:ro
      - /vol3/.beszel:/extra-filesystems/sdb1:ro
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb

**Comment by Haorran** [comment]
我也在跟踪这个Feature，希望Agent能智能的识别到硬盘的序列号以此稳定的显示

**Comment by incaseoftrouble** [comment]
Hi, I also have this issue, copying a possible solution from the duplicate (didn't find this issue here):

One thing that could work would be an optional mapping from disk ID to reporting name. So, for example, as environment variable I can write `ata-ST16000NM001G-2KK103_SERIAL:sda,ata-ST...:sdb,...`. The daemon then reads the symlink `/dev/disk/by-id/ata-...` and checks which kname this currently links to (say `/dev/sdb`) (probably there is a `/proc` entry for this, too?). It then knows that whatever we currently are reading for `/dev/sdb` should be reported to the hub as `/dev/sda`. In case this is not bijective, report an error.

As I understand it, the tricky bit with reading labels etc. is that `/proc/diskstats` just reports the (effectively ephemeral) KNAME, so there needs to be something that establishes the relationship between the current KNAME and the permanent reporting name.

**Comment by valentinomariotto** [comment]
Hi all, using /dev/disk/by-id worked for me

find your devices ids:
`ls -la /dev/disk/by-id/ | grep -Ev 'part[0-9]|^total'`

  ```
beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:alpine # alpine is required for SMART monitoring
    restart: always
    network_mode: host
    volumes:
      - beszel_agent_data:/var/lib/beszel-agent
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/downloads/.beszel:/extra-filesystems/sdX1__Downloads:ro
      # other mounts
    environment:
      LISTEN: 45876
      KEY: 'ssh-****' # hub's public key
      
      # agent to hub connection
      TOKEN: ****
      HUB_URL: http://127.0.0.1:8090
    devices: # for smart monitoring
      # /dev/sda is used by the container root volume
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_5PK07KAF:/dev/sdb # raid1 member 12tb
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_5PKV8KYF:/dev/sdc # raid1 member 12tb
      - /dev/disk/by-id/ata-Samsung_SSD_870_QVO_1TB_S5RRNF1R704865W:/dev/sdd # SSD 1tb
      - /dev/disk/by-id/ata-ST9750420AS_5WS4C4QN:/dev/sde # downloads 0.75tb
    cap_add:
      - SYS_RAWIO # required for S.M.A.R.T. data
      - SYS_ADMIN # required for NVMe S.M.A.R.T. data
```
