### ISSUE TITLE
Question: SystemID changing when updating

### ISSUE THREAD

**Issue by rcbop** [henrygd/beszel#335]
Hello, I have a question does the systemID always change when my [watchtower](https://containrrr.dev/watchtower/) updates the beszel image to the latest version? Can I do something to persist this systemId?

I'm asking this because when it restarts and changes the systemId it's breaking this integration https://gethomepage.dev/widgets/services/beszel/

**Comment by henrygd** [comment]
Strange, I'm not sure why that would happen. This is something you noticed with previous releases as well?

If you look at the `created` date for the system on `/_/#/collections?collection=systems` does it indicate that it was recreated?

Are you using a config file to define systems by any chance?

I'll look further into it. Thanks for letting me know.

**Comment by rcbop** [comment]
Hey @henrygd 
This is how I was setting this up:

```
 beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - /opt/docker-services/data/config/beszel:/beszel_data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`beszel.mydomain.com`)
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.services.beszel.loadbalancer.server.port=8090
      - homepage.group=Infrastructure
      - homepage.name=Beszel
      - homepage.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/webp/beszel-light.webp
      - homepage.href=https://beszel.mydomain.com
      - homepage.description=Monitoring solution
      - homepage.widget.type=beszel
      - homepage.widget.url=https://beszel.mydomain.com
      - homepage.widget.username=xxxxx@email.com
      - homepage.widget.password=xxxxxxx
      - homepage.widget.systemId=rrsa25j8p920ukn # <-- tried updating this to the latest change found in https://beszel.mydomain.com/_/#/collections?collectionId=2hz5ncl8tizk5nx&collection=_pb_users_auth_&filter=&sort=-%40rowid but no luck here
```

And now I get this error in the homepage UI.

```
API Error: Invalid character in header content ["Authorization"]
URL: https://beszel.mydomain.com/api/collections/systems/records?page=1&perPage=500&sort=%2Bcreated
Raw Error:
{
    "code": "ERR_INVALID_CHAR",
    "level": "error"
}
```

Everything should be on latest version since I'm running watchtower to pull the latest image from registries.
