### ISSUE TITLE
cannot log in

### ISSUE THREAD

**Issue by pixelcola** [henrygd/beszel#346]
I created a user, but I cannot log in, but can log in `/_/#/settings`

compose.yml
```yml
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    volumes:
      - ./data:/beszel_data
    restart: unless-stopped
    ports:
      - 8090:8090
    networks:
      - cloudflared

networks:
  cloudflared:
    driver: bridge
    external: true
```
 The `/api/collections/users/auth-refresh` API returns `400 Bad Request`, response is: 
```json
{
    "data": {},
    "message": "Something went wrong while processing your request.",
    "status": 400
}
```

 The `/api/realtime` API returns `403 Forbidden`, response is: 
```json
{
    "data": {},
    "message": "The current and the previous request authorization don't match.",
    "status": 403
}
```
