### ISSUE TITLE
Unable to Connect to Local Beszel Agent in Docker

### ISSUE THREAD

**Issue by ericukk** [henrygd/beszel#359]
I’m running into issues trying to connect to the local Beszel agent using the Docker setup provided in the getting started guide. Here is the relevant part of the `docker-compose.yml` I’m using:

```yaml
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: 'redacted'
```

After running `docker compose down && docker compose up -d`, the `beszel-agent` container is listed as “down,” and the logs don’t show any attempts to connect:

![image](https://github.com/user-attachments/assets/bdc31e7c-f56e-4bb3-9548-4b417d1b1586)

```
docker compose logs -f -n 100
beszel-agent  | 2024/12/31 23:08:27 INFO Root disk mountpoint=/ io=sda
beszel        | 2024/12/31 23:08:28 Server started at http://0.0.0.0:8090
beszel        | ├─ REST API:  http://0.0.0.0:8090/api/
beszel        | └─ Dashboard: http://0.0.0.0:8090/_/
beszel-agent  | 2024/12/31 23:08:27 INFO Detected network interface name=wlan0 sent=24551158 recv=25407343
beszel-agent  | 2024/12/31 23:08:27 INFO Detected network interface name=tailscale0 sent=26720 recv=58350
beszel-agent  | 2024/12/31 23:08:27 INFO Starting SSH server address=:45876
```

The `beszel` container is running fine, but I'm unable to figure out why the agent is not connecting. The agent logs don't show much info, and without shell access or `nc` inside the container, debugging is tricky.

Anyone have suggestions or insights into what might be causing this issue?

Beszel version 0.9.0
Raspberry Pi 4 on NixOS 24.11
cgroup memory is enabled

**Comment by henrygd** [comment]
Do you see errors on the logs page at `/_/#/logs`?

Scratch images are nice, but I agree it's annoying to debug something like this with no shell available. Maybe I'll add an `:alpine` image to make the process easier.

**Comment by ericukk** [comment]
Thanks for the quick response.
It seems that there was a connection problem when I tried to start it up the first time.

![image](https://github.com/user-attachments/assets/08cc78a9-11a7-4240-82cc-49b79c23f45c)

I just tried to compose down and up again but it's only INFO logs of successful http requests.
I'll see if I can copy some tools into the container to try to get more information.

**Comment by ericukk** [comment]
I believe I've figured out the issue and can now make it work. I recompiled the container using Alpine based on your suggestion, which was really helpful for debugging. 

From the container, I could ping `host.docker.internal` and connect to other ports on my host, but not to 45876. After further debugging, I realized the issue was with the firewall. Once I opened it, everything worked.

I'll investigate why I didn’t need to do that when I tried to replicate on my Fedora setup, but only on NixOS. It might be due to some different default settings.

Thanks a lot for your help. I learned a great deal. Happy new year.

**Comment by henrygd** [comment]
Interesting, thanks for the update!

I wonder if you would be able to connect from the host using `telnet localhost 45876` with the firewall active, or if it's specifically a problem connecting from a container via `host.docker.internal`.

**Comment by ericukk** [comment]
I tried with both firewall active and inactive, however telnet with localhost didn't work. 
I guess that's because the network is isolated. When I tried `ss -tuln` I could only see 8090 listening.

**Comment by Ge0rg3** [comment]
Thanks @ericukk! Running `sudo ufw allow from 127.0.0.1 to any port 45876` did the trick for me after following your advice. It could be good to get this added to the Getting Started page :)

**Comment by henrygd** [comment]
Thanks, I'll look further into this and mention it next time I update the docs.

**Comment by Fumler** [comment]
> Thanks @ericukk! Running `sudo ufw allow from 127.0.0.1 to any port 45876` did the trick for me after following your advice. It could be good to get this added to the Getting Started page :)

Just to add my 2 cents in case someone stumbles upon this issue when using custom docker networks. Do `docker network ls` and then `docker network inspect your-custom-network`. Find the `[0].IPAM.Config[0].Subnet` property and allow that through your firewall on your host, e.g.. `sudo ufw allow from 172.18.0.0/16 to any port 45876`

**Comment by gelomon** [comment]
> Just to add my 2 cents in case someone stumbles upon this issue when using custom docker networks. Do `docker network ls` and then `docker network inspect your-custom-network`. Find the `[0].IPAM.Config[0].Subnet` property and allow that through your firewall on your host, e.g.. `sudo ufw allow from 172.18.0.0/16 to any port 45876`

Thanks for this, I was exposing beszel so I can easily access and was not able to make the network monitoring working. I stumbled upon this comment and added the ufw rule for the network that baszel is running and now it works flawlessly!

**Comment by Chinoman10** [comment]
To me, the issue was that Docker Desktop didn't have the option "Enable host networking" on.
It's 'buried' under Settings > Resources > Network ...

Now the port 45876 is being properly exposed on the host, although I'm still having issues connecting to it through CF tunnels, but that's a separate issue to troubleshoot...

**Comment by henrygd** [comment]
@sysop76 Please ignore that, everything should work as intended.

**Comment by sysop76** [comment]
> [@sysop76](https://github.com/sysop76)그건 무시하세요. 모든 것이 의도한 대로 작동해야 합니다.

Ah... I found the answer. The reason it didn't work was because the firewall was turned on while running with Docker, so I allowed the Docker virtual IP (172.xx.xx.xx) range in the firewall and it worked normally.

**Comment by phuongnam-code** [comment]
I also don't know why it didn't work until I stopped UFW and restarted it then it worked (Ubuntu server 22.04)
`sudo systemctl stop ufw`
`sudo systemctl restart ufw`
```
services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: 45876
      KEY: "my-key"
```
