### ISSUE TITLE
Container stats missing with socket-proxy?

### ISSUE THREAD

**Issue by goncalossilva** [henrygd/beszel#368]
Hey, and thanks for creating this project!

I migrated to `socket-proxy` yesterday and lost all individual container stats. Everyting else is fine. In the backend, I can see that table is just empty.

No errors in the logs:

```
2025/01/05 17:09:51 Server started at http://0.0.0.0:8090

├─ REST API:  http://0.0.0.0:8090/api/

└─ Dashboard: http://0.0.0.0:8090/_/
```

And:

```
2025/01/05 17:09:51 INFO Root disk mountpoint=/ io=sda

2025/01/05 17:09:51 INFO Detected network interface name=enp6s18 sent=32976148128417 recv=1927194881807

2025/01/05 17:09:51 INFO DOCKER_HOST host=tcp://socket-proxy:2375

2025/01/05 17:09:51 INFO Starting SSH server address=:45876
```

Here is my compose file:

```
services:
  beszel:
    image: 'henrygd/beszel:latest'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8090:8090'
    volumes:
      - '/var/mounts/beszel/beszel_data:/beszel_data'
  beszel-agent:
    image: 'henrygd/beszel-agent:latest'
    restart: unless-stopped
    network_mode: host
    environment:
      - 'DOCKER_HOST=tcp://socket-proxy:2375'
      - PORT=45876
      - >-
        KEY=ssh-ed25519
        AAAAC3NzaC1lZDI1NTE5AAAAIKN1E5TF2lzh4Otb2sfyMY0b7jVFRD26UlZ4UhB5owN9
  socket-proxy:
    image: 'lscr.io/linuxserver/socket-proxy:latest'
    restart: unless-stopped
    environment:
      - CONTAINERS=1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    read_only: true
    tmpfs:
      - /run
```

I've made a few vain attempts at making this work, mostly by increasing permissions (`POST=1`, `ALLOW_RESTARTS=1`, `ALLOW_RESTARTS=1`, `ALLOW_START=1`, `ALLOW_STOP=1`) eventually abandoning brute-force and actually reading the code of both projects.

Unfortunately, reading the pertinent parts ([ref](https://github.com/henrygd/beszel/blob/main/beszel/internal/agent/docker.go), [ref](https://github.com/Tecnativa/docker-socket-proxy/blob/master/haproxy.cfg)) doesn't really tell me why this would break. It seems like it should just work!

Does anyone else have any hints on why container stats would be missing in such a simple setup?

**Comment by henrygd** [comment]
This is a bit confusing so I'll make a note to mention this in the docs.

Because the agent uses `network_mode: host`, it cannot resolve the proxy using the hostname `socket-proxy`. They are in different networks.

The solution is to expose the the proxy on localhost (this does not allow external connections), then use localhost to connect from the agent.

```yml
services:
  beszel-agent:
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
  socket-proxy:
    ports:
      - 127.0.0.1:2375:2375
```

Let me know if you have any trouble with this!
