### ISSUE TITLE
GPUs showing on some systems but not others

### ISSUE THREAD

**Issue by henrygd** [henrygd/beszel#375]
Context: https://github.com/henrygd/beszel/issues/262#issuecomment-2574043919

**Comment by henrygd** [comment]
@SonGokussj4 Let's move discussion about the missing GPUs here please so everyone in the main GPU thread isn't notified.

**Comment by SonGokussj4** [comment]
And then there was even weirder error :-) On a yet different machine.

```bash
user@frankenstein:~/beszel-agent$ nvidia-smi
Tue Jan  7 00:57:08 2025
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2070        Off | 00000000:01:00.0 Off |                  N/A |
| 57%   23C    P8               2W / 175W |      1MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
user@frankenstein:~/beszel-agent$ nvidia-smi -l 4 --query-gpu=index,name,temperature.gpu,memory.used,memory.total,utilization.gpu,power.draw --format=csv,noheader,nounits
0, NVIDIA GeForce RTX 2070, 23, 1, 8192, 0, 2.62
0, NVIDIA GeForce RTX 2070, 23, 1, 8192, 0, 2.78

user@frankenstein:~/beszel-agent$ docker compose up -d
[+] Running 0/0
 ⠋ Container beszel-agent  Creating                                                                                0.0s
Error response from daemon: unknown or invalid runtime name: nvidia

$ docker --version
Docker version 24.0.7, build 24.0.7-0ubuntu2~22.04.1
```

**Comment by Hilbsam** [comment]
Okay, to be clear on your second (not working machine) in your docker-compose.yml you added GPU:"true", right? Because in your example it is missing.

It should look something like this:
```
services:
  beszel-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    runtime: nvidia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: "ssh-ed25519 AAAAC3...aJ34gQE+"
      GPU: "true"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # <---- We have 1 or 2 or 3 GPUs in our servers
              capabilities:
                - gpu
```

If that wasn't your problem:

- What OS and version of the OS is the machine? I know that Windows with wsl2 can do some "nice" behaviors
- What GPU driver version do you have installed?
- Does the normal Docker example for the GPU work on your machine? Link: https://docs.docker.com/desktop/features/gpu/
