### ISSUE TITLE
Features request : time range selection and disks exclusion

### ISSUE THREAD

**Issue by Ostantia** [henrygd/beszel#405]
Hello,

First, big thanks for this project, it's really super useful and impressive!

To improve it, I suggest adding the following features : 
 - time range selection for graphs.
 What I mean by this is that Beszel will be used for "after incident" analysis. 
And if a problem was detected in the metrics two days ago and you weren't able to go and resolve or search for the root cause in this time, then what you're left with is to use the 1 week graphs preset which cuts every 2 hours of metrics, taking away the precision of the stats.
This could be resolved if the ability to set time ranges what's added, like if you want to see the graphs of the day before, you could have something like "from day-1 at 00:00:00 to day at 23:59:99".

 - The ability to exclude disks from the graphs. I personally have many disks and partitions on my server, some of which are full or nearly full but in intentional way. The problem is that they will trigger an alert even if the root volume for example is only at 14% of used space.

Thanks again for this amazing project and for reading my request!

**Comment by henrygd** [comment]
No worries!

The longer graphs are made by averaging the data of the shorter graphs. So all data is accounted for, but it's smoothed out somewhat because each data point represents a longer period of time.

I don't want to keep every one minute record indefinitely because this could lead to scaling issues.

Maybe we can give agents their own db to store their data, then stream in old records on demand if needed. Or use something like nats jetstream.

When you say "ability to exclude disks from the graphs" -- do you mean exclude them from alerts, or exclude them from being monitored entirely?

**Comment by Ostantia** [comment]
Hello,

Thanks for your answer to my request.

I meant initially excluding them completely from monitoring but actually the other solution seems beter.

My biggest problem was that the level of usage of some disks in my server is very high but even if it's full it will not need any human intervention or correction (like a non critical thing)

But because of them I could not enable the supervision at all for, for exemple, my root disk because the alert will always be triggered because of the mentionned non critical disks/partitions.

So just excluding disks from the alerting system seems much beter now that you mention it, because it allows to still be able to check their usage from time to time, or even just have some usage metrics.

**Comment by Ostantia** [comment]
Okay, thanks for the reply !

Just as a side note, all of the filesystems of the whole host server where added to the interface from the moment I mounted the root filesystem by a bind mount (will post my "secrets free" docker compose here as an example) :
```
services:
  beszel:
    image: henrygd/beszel:latest
    restart: unless-stopped
    container_name: private-beszel-01
    hostname: private-beszel-01
    storage_opt:
      size: 1G
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 300M
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - storage-manager_private-beszel-01_data:/beszel_data

  beszel-agent:
    image: henrygd/beszel-agent:latest
    restart: unless-stopped
    container_name: private-beszelagent-01
    hostname: private-beszelagent-01
    storage_opt:
      size: 1G
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 300M
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/extra-filesystems/root:ro
    environment:
      PORT: 45876
      # Do not remove quotes around the key
      KEY: '<REDACTED>'

volumes:
  storage-manager_private-beszel-01_data:
    external: true

networks:
  default:
    external: true
    name: docker-compose_default
```

I think that I could resolve it by mounting the LVM volume instead (will try when possible) but for people not using logical volumes I don't know if there is any solution.
