### ISSUE TITLE
Docker Secret Support

### ISSUE THREAD

**Issue by beny2000** [henrygd/beszel#411]
Hi, love the project. It's the most straightforward approach to monitoring I've come across. I was wondering if there is (or will be) Docker secret support for environment variables. I'd like to be able to specify the agent key in a Docker secret and pass the file path as the environment variable, as is common with other services.

For example, being able to do something like this would be great
```yaml
beszel-agent:
  image: henrygd/beszel-agent
  network_mode: host
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  environment:
    PORT: 45879
    KEY_FILE: /run/secrets/beszel_agent_key
  secrets:
     - beszel_agent_key
```

Thanks

**Comment by beny2000** [comment]
Added support for this in #412

**Comment by henrygd** [comment]
Thanks, I'll check it out tomorrow.

**Comment by arunoruto** [comment]
The `KEY_FILE` support will make it easier to support a `nix` service module in the future!

**Comment by henrygd** [comment]
Sorry about that. The next release has been a bit delayed but I hope to have it wrapped up in the next few days.

**Comment by jo-chemla** [comment]
No worries and no need to rush, it's open-source!

**Comment by floari** [comment]
Hi!

Is this still in development? Using 

`KEY_FILE=/run/secrets/beszel_agent_key`

does not seem to work currently.

**Comment by henrygd** [comment]
@floari It should work, I just forgot to close the issue. What do your agent logs look like?

**Comment by floari** [comment]
@henrygd beszel-agent logs: 
`2025/04/21 08:45:53 Failed to load public keys:failed to read key file: open /run/secrets/beszel_agent_key: no such file or directory
`

compose.yml
`
 environment:
    - LISTEN=/beszel_socket/beszel.sock
    # Do not remove quotes around the key
    - KEY_FILE=/run/secrets/beszel_agent_key

secrets:
  beszel_agent_key:
    file: /secrets/beszel/BESZEL_AGENT_KEY
`

Anything I am missing?

**Comment by arunoruto** [comment]
> [@henrygd](https://github.com/henrygd) beszel-agent logs: `2025/04/21 08:45:53 Failed to load public keys:failed to read key file: open /run/secrets/beszel_agent_key: no such file or directory `
> 
> compose.yml
> 
> ```
>  environment:
>     - LISTEN=/beszel_socket/beszel.sock
>     # Do not remove quotes around the key
>     - KEY_FILE=/run/secrets/beszel_agent_key
> 
> secrets:
>   beszel_agent_key:
>     file: /secrets/beszel/BESZEL_AGENT_KEY
> ```
> 
> Anything I am missing?

Linux paths are case sensitive. Try running `ls /run/secrets` inside the container (with `docker exec -it <container name> <command>`). Maybe you will need to comment out the `KEY_FILE` env var from the compose file.
My guess is, the file is present in all capital letters in the path, but you should check if really anything is present.

**Comment by floari** [comment]
Following error:
`OCI runtime exec failed: exec failed: unable to start container process: exec: "ls": executable file not found in $PATH: unknown
`

Dunno whats wrong. This is the default I am using with all my containers.

**Comment by henrygd** [comment]
It's a scratch image but there are instructions in the docs if you want to get into the container to troubleshoot: https://beszel.dev/guide/docker-shell

I don't use swarm so I'm not super familiar with secrets, but it seems like this should work:

```yml
services:
   beszel-agent:
     environment:
       KEY_FILE: /run/secrets/beszel_agent_key
     secrets:
       - beszel_agent_key

secrets:
   beszel_agent_key:
     file: /secrets/beszel/BESZEL_AGENT_KEY
```
