### ISSUE TITLE
[Bug]: Can't see SWAP Graph

### ISSUE THREAD

**Issue by Tom5421** [henrygd/beszel#541]
### Description

On one of my systems I have SWAP enabled but I can't see any graphs in Beszel for it. See output of `free -h` below. 

```
               total        used        free      shared  buff/cache   available
Mem:            7.8Gi       3.2Gi       1.5Gi       256Mi       3.1Gi       4.5Gi
Swap:          2.0Gi       768Ki       2.0Gi
```

### Expected Behavior

I should be able to see the SWAP graph. 

### Steps to Reproduce

Setup Beszel agent via Docker and no SWAP graphs appear. 

### OS / Architecture

Docker / Linux Ubuntu 24.04 LTS

### Beszel version

0.9.1

### Installation method

Docker

### Configuration

```yaml
services:
  beszel-agent:
    image: henrygd/beszel-agent:0.9.1
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: "<key>"
```

### Hub Logs

```json

```

### Agent Logs

```shell

```
