### ISSUE TITLE
[Bug]: BESZEL_HUB_APP_URL not being sent in notifications

### ISSUE THREAD

**Issue by bwees** [henrygd/beszel#598]
### Description

I set BESZEL_HUB_APP_URL to my instance URL so that notification links would take me to the proper page. However when running test notifications, I am still seeing localhost:8090 as my base URL

<img width="244" alt="Image" src="https://github.com/user-attachments/assets/65a8d6f2-a96a-4c08-bd8b-424c0b1a21df" />

The environment variable is set in my compose file (see below) and Portainer reports it set on the container as well. Is there some step that I'm missing?

### Expected Behavior

BESZEL_HUB_APP_URL should be used instead of localhost:8090 for notifications.

### Steps to Reproduce

Set BESZEL_HUB_APP_URL to a custom URL and send a test notification (in my case, Discord).

### OS / Architecture

linux/amd64

### Beszel version

0.9.1

### Installation method

Docker

### Configuration

```yaml
beszel:
    image: henrygd/beszel
    restart: unless-stopped
    volumes:
      - /home/bwees/storage/beszel:/beszel_data
    networks:
      - traefik_backend
    environment:
      - BESZEL_HUB_APP_URL=https://beszel.bwees.lab
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"

      - "traefik.http.routers.beszel.rule=Host(`beszel.bwees.lab`)"
      - "traefik.http.routers.beszel.service=beszel"
      - "traefik.http.routers.beszel.entrypoints=websecure"
      - "traefik.http.routers.beszel.tls=true"
```

### Hub Logs

```json

```

### Agent Logs

```shell

```
