### ISSUE TITLE
[Feature]: Ansible playbooks for install/uninstall inside

### ISSUE THREAD

**Issue by hellofaduck** [henrygd/beszel#628]
### Describe the feature you would like to see

I made ansible playbook for my k3s installations and want to share my solution if someone searching for this stuff.
Deleting role
```
- name: Remove beszel-agent if service exists
  block:
    - name: Populate service facts
      ansible.builtin.service_facts:
    
    - name: Download install-agent.sh script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-agent.sh
        dest: /tmp/install-agent.sh
        mode: '0755'  # Set executable permissions
      when: ansible_facts['services']['beszel-agent.service'] is defined
    
    - name: Remove beszel agent
      become: true
      ansible.builtin.command:
        cmd: /tmp/install-agent.sh -u
      when: ansible_facts['services']['beszel-agent.service'] is defined
```
Installation role with service existing check:
```
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Download the install-agent.sh script
  get_url:
    url: https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-agent.sh
    dest: /tmp/install-agent.sh
    mode: '0755'  # Set executable permissions
    
- name: Remove beszel agent if service exists
  become: true
  ansible.builtin.command:
    cmd: /tmp/install-agent.sh -u
  when: ansible_facts.services['beszel-agent.service'] is defined

- name: Run the install-agent.sh script
  shell: |
    if [ "{{ beszel_agent_autoupdate }}" = "true" ]; then 
      yes | /tmp/install-agent.sh -p {{ beszel_agent_ssh_port }} -k "{{ beszel_agent_ssh_key }}"
    else 
      yes N | /tmp/install-agent.sh -p {{ beszel_agent_ssh_port }} -k "{{ beszel_agent_ssh_key }}" 
    fi
  ignore_errors: false
```

### Describe how you would like to see this feature implemented

Its ready to use yaml
