### ISSUE TITLE
[Bug]: Error with custom sensor path

### ISSUE THREAD

**Issue by ameer1234567890** [henrygd/beszel#643]
### Description

I am getting below error with version v0.10.0
```
2025/03/06 09:36:43 INFO SYS_SENSORS path=/mnt/sys
panic: cannot create context from nil parent
goroutine 1 [running]:
context.WithValue({0x0?, 0x0?}, {0x7af240?, 0xc000102250?}, {0x7deee0?, 0xc0001007e0?})
	/usr/local/go/src/context/context.go:720 +0x14d
beszel/internal/agent.NewAgent()
	/app/internal/agent/agent.go:59 +0x3a5
main.main()
	/app/cmd/agent/agent.go:132 +0x179
```

My `docker-compose.yml` is as below:
```
services:
  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:latest
    restart: unless-stopped
    network_mode: host
    environment:
      PORT: 45876
      KEY: ssh-ed25519 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      SYS_SENSORS: /mnt/sys
      SENSORS: battery
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/mmc1/.beszel:/extra-filesystems/mmc1:ro
      - /mnt/sys:/mnt/sys
```

Output of `ls -l /mnt/sys`
```
total 8
drwxr-xr-x 3 root root 4096 Sep 17 16:56 class
drwxr-xr-x 3 root root 4096 Sep 17 16:56 devices
```

Note that the same configuration works in v0.9.1

### Expected Behavior

Working as it did in v0.9.1

### Steps to Reproduce

As described above

### OS / Architecture

linux/amd64 (agent)

### Beszel version

0.10.0

### Installation method

Docker

### Configuration

```yaml

```

### Hub Logs

```json

```

### Agent Logs

```shell

```
