### ISSUE TITLE
[Bug]: Node data gets mixed up (after one of my swarm nodes went down)

### ISSUE THREAD

**Issue by Stitch10925** [henrygd/beszel#671]
### Description

Setup:

I am running Docker Swarm with multiple nodes. The agents are globally installed and have their ports exposed on the host interface to prevent cross-talk within the Docker networks. Each agent is added to Beszel using their public IP address, again to prevent cross-talk.

Now, I'm not sure how the agents collect their data, but I'm seeing data being mixed between nodes. In the graphs it shows me data of services that are running on other nodes. I noticed this because one of my nodes went down, which seemed to report data correctly, but after it came back up the data was wrong. I then investigated my other nodes and came to the same conclusion.

Here a screenshot of the reported data before and after the node went down:

Before:
![Image](https://github.com/user-attachments/assets/8370aecd-68a1-4e57-90a5-f71239a3e01d)

After:
![Image](https://github.com/user-attachments/assets/965c9751-99df-4e69-aafd-7079c310fe7a)

As you can see, it is showing completely different services. My services are confined to specific nodes, so it is not possible for these services to run on that node (and they are not, I checked).

So I'm wondering if either the way the agents collect the data causes data mix-up, or if maybe something is wrong in the database, or if maybe I configured something incorrectly? How does Beszel keep the data separated, by IP, Hostname, somethign else?

I have another non-docker server I have running which I am also monitoring using Beszel, and this one seems to report correctly.

### Expected Behavior

I expect each node to only show the data from the services running on said node, and not from other nodes.

### Steps to Reproduce

Run Docker swarm with multiple nodes, with the nodes running agents with their port exposed in host mode. Then add these agents to Beszel server using the node's IP address.

### OS / Architecture

Alpine Linux

### Beszel version

0.9.1

### Installation method

Docker

### Configuration

```yaml
version: '3.8'
services:
  app:
    image: henrygd/beszel:0.9.1
    ports:
    - 8091:8090
    volumes:
    - beszel:/beszel_data
    environment:
      DISABLE_PASSWORD_AUTH: "false"
    deploy:
      restart_policy:
        window: 5s
      placement:
        constraints:
         - node.labels.host==intsrvc
  
  agent:
    image: henrygd/beszel-agent:0.9.1
    ports:
    - target: 45876
      published: 45876
      protocol: tcp
      mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LOG_LEVEL: "debug"
      PORT: 45876
      KEY: "REDACTED"
    deploy:
      mode: global
      restart_policy:
        window: 5s

volumes:
  beszel:
```

### Hub Logs

```json

```

### Agent Logs

```shell

```
