### ISSUE TITLE
[Bug]: Beszel Hub not starting after update [Docker] - Error: failed to parse config.yml

### ISSUE THREAD

**Issue by winkelement** [henrygd/beszel#680]
### Description

Beszel Hub Docker Container is failing to start with error:
```
beszel exited with code 0
beszel  | Error: failed to parse config.yml: yaml: unmarshal errors:
beszel  |   line 25: cannot unmarshal !!seq into string
beszel  | Error: failed to parse config.yml: yaml: unmarshal errors:
beszel  |   line 25: cannot unmarshal !!seq into string
beszel  | Error: failed to parse config.yml: yaml: unmarshal errors:
beszel  |   line 25: cannot unmarshal !!seq into string
beszel  | Error: failed to parse config.yml: yaml: unmarshal errors:
beszel  |   line 25: cannot unmarshal !!seq into string
beszel  | Error: failed to parse config.yml: yaml: unmarshal errors:
beszel  |   line 25: cannot unmarshal !!seq into string
beszel  | Error: failed to parse config.yml: yaml: unmarshal errors:
beszel  |   line 25: cannot unmarshal !!seq into string
beszel  | Error: failed to parse config.yml: yaml: unmarshal errors:
beszel  |   line 25: cannot unmarshal !!seq into string
beszel  | Error: failed to parse config.yml: yaml: unmarshal errors:
beszel  |   line 25: cannot unmarshal !!seq into string
beszel  | Error: failed to parse config.yml: yaml: unmarshal errors:
beszel  |   line 25: cannot unmarshal !!seq into string
beszel exited with code 0
beszel exited with code 0
beszel  | Error: failed to parse config.yml: yaml: unmarshal errors:
beszel  |   line 25: cannot unmarshal !!seq into string
beszel exited with code 0
```

### Expected Behavior

Docker Container should start (without errors).

### Steps to Reproduce

* `docker compose pull`
* `docker compose up`

### OS / Architecture

linux/amd64 (hub)

### Beszel version

0.10.2

### Installation method

Docker

### Configuration

```yaml
docker-compose.yml


services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
```

### Hub Logs

```json

```

### Agent Logs

```shell

```

**Comment by winkelement** [comment]
So this is caused by having a system name starting with a square bracket (`[`) in my config.yml.

````
systems:
    - name: [pve]
      host: xxx.xxx.xxx.xxx
      port: 45876
      users:
        - XXX
````

* Only seems to be a problem when at the beginning at the name, anywhere els square brackets work fine
* Worked just fine after the last update 0.10.1

I fixed it by adding double quotes around the name.
````
systems:
    - name: "[pve]"
      host: xxx.xxx.xxx.xxx
      port: 45876
      users:
        - XXX
````
