### ISSUE TITLE
How can we run both the hub and the agent on a single machine?

### ISSUE THREAD

**Issue by dkorecko** [henrygd/beszel#73]
Hello,

First and foremost, the UI looks wonderful. I'm just struggling with getting the agent to connect to the hub.

Hub docker-compose:
```services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - '1625:8090'
    volumes:
      - ./beszel_data:/beszel_dat
```

Agent docker-compose:
```services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: "REDACTING"
      # FILESYSTEM: /dev/sda1 # set to the correct filesystem for disk I/O stats
```

No errors in the logs.
![image](https://github.com/user-attachments/assets/6ab445d4-6772-4a41-bd1b-af8fe3ffff8c)

Any help would be greatly appreciated.

The IP I've used when adding the server was 127.0.0.1.

**Comment by henrygd** [comment]
Try this and add the system with host `host.docker.internal`

```yml
services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - '1625:8090'
    volumes:
      - ./beszel_data:/beszel_data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: "REDACTED"
```

Let me know if that doesn't work for you.

**Comment by dkorecko** [comment]
That solved it, maybe would be good to add this into the troubleshooting section as a possible solution?

**Comment by psychowood** [comment]
> Try this and add the system with host `host.docker.internal`
> 
> ```yaml
>     extra_hosts:
>       - "host.docker.internal:host-gateway"
> ```
> 
> Let me know if that doesn't work for you.

Does this provide something different than just using the container hostname, as long as the network is shared?

```yaml
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    volumes:
      - ./beszel_data:/beszel_data
    networks:
      reverse-proxy:

  beszel-agent:
    image: 'henrygd/beszel-agent'
    container_name: 'beszel-agent'
    hostname: beszel-agent
    restart: unless-stopped
#    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: 'ssh-ed25519 XXX'
      FILESYSTEM: /dev/sdb1 # set to the correct filesystem for disk I/O stats
    networks:
      reverse-proxy:
````

(I disabled host networking since I don't need global network monitoring, I'm eagerly waiting for container network data tracking :) )

**Comment by henrygd** [comment]
> Maybe would be good to add this into the troubleshooting section as a possible solution?

Will do.

> Does this provide something different than just using the container hostname, as long as the network is shared?

Nope, it's just a way to access a container when one is in host network mode and the other is not. Not something you need otherwise.

**Comment by gharden91** [comment]
In case anyone else is running beszel on a Mac with Docker Desktop and Compose...
I got this from Claude and it's currently working for me.

For the beszel hub: You don't need to specify the `extra_hosts and "host.docker.internal:host-gateway"`
On the beszel agent: specify the ports instead of using `network_mode:host`
On the hub: Create the new system using host/ip of `host.docker.internal`
```
services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - ./beszel_data:/beszel_data

  beszel-agent:
    image: 'henrygd/beszel-agent'
    container_name: 'beszel-agent'
    restart: unless-stopped
    ports:
      - '45876:45876'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: '...'
```

I have not fact checked this at all beyond it working. Claude 3.5 Sonnet says:

> Running on Docker Desktop for Mac does affect how extra_hosts works, and it explains why you might be experiencing issues. Docker Desktop for Mac uses a virtualization layer, which changes how networking between containers and the host machine works.
> For Docker Desktop on Mac, the host.docker.internal hostname is actually built-in and should work without needing to specify it in extra_hosts. Here's what you need to know:
> - Remove extra_hosts: You can remove the extra_hosts section entirely from your Docker Compose file. It's not necessary for Docker Desktop on Mac.
> - Use host.docker.internal: Inside your container, you can use host.docker.internal to reference your host machine without any additional configuration.
> - Ports: Ensure that any services you're trying to reach on your host machine have their ports exposed and are not blocked by your Mac's firewall.
> - Network mode: The network_mode: host that you're using for beszel-agent doesn't work the same way on Docker Desktop for Mac as it does on Linux. On Mac, it doesn't actually share the host's network stack due to the virtualization layer.
