### ISSUE TITLE
[Bug]: API integration with Homepage

### ISSUE THREAD

**Issue by Matt-UKTX** [henrygd/beszel#732]
### Description

First off, I am using Beszel and love it.  It does what it took me a week to build in Grafana, Prometheus, Node Exporter, etc.  What a great piece of software.

I also use Homepage (gethomepage.dev) as my main dashboard.  It has a pre-built widget for Beszel, but for some reason, I just cannot get it to work.  (https://gethomepage.dev/widgets/services/beszel/). Not sure what I am doing wrong.  Here is the code snipped from my Homepage config.
 
>     - Beszel:
>         icon: beszel.svg
>         description: Beszel
>         widget:
>             type: beszel
>             url: http://192.168.100.100:8090
>             username: admin
>             password: mypassword
>             systemId: <id copied from Systems table in PocketBase>
>             version: 2 

The error I get is: 
API Error: No items returned from beszel API

### Expected Behavior

Widget should load...

### Steps to Reproduce

See above

### OS / Architecture

Linux / Synology NAS

### Beszel version

Latest

### Installation method

Docker

### Configuration

```yaml

```

### Hub Logs

```json

```

### Agent Logs

```shell

```

**Comment by henrygd** [comment]
Resolved in https://github.com/gethomepage/homepage/discussions/5125

**Comment by ramazansancar** [comment]
<img width="525" height="684" alt="Image" src="https://github.com/user-attachments/assets/85bbfe6b-9785-4c31-bfd9-fd58ba6f006f" />

Same issue

```yml
    - Beszel:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/beszel.svg
        href: http://192.168.1.200:8090
        ping: http://192.168.1.200:8090
        description: Beszel - Docker Monitoring
        server: my-docker
        container: beszel
        showStats: true
        widget:
            type: beszel
            url: http://192.168.1.200:8090
            username: -----
            password: -----
            systemId: g0ghslq6wbvwpp0 # optional
            version: 2 # optional, default is 1
```


http://192.168.1.200/api/services/proxy?group=Bilgi&service=Beszel&endpoint=systems

```json
{
  "data": {},
  "message": "The requested resource wasn't found.",
  "status": 404
}
```
