### ISSUE TITLE
[Bug]: Docker Network I/O not reporting correct traffic

### ISSUE THREAD

**Issue by truncsphere** [henrygd/beszel#783]
### Description

I noticed that my Docker system isn't reporting correct network usage for all containers for a given time. This is compared to Grafana which shows the network usage for each container during the same time (as well as my firewall alert). 

### Expected Behavior

Each container should show the correct network i/o for a given time. However I'm seeing discrepancies between what is being reported in Grafana vs Beszel. 

### Steps to Reproduce

Below are the same time period for Grafana and Beszel. As can be seen at the times stamp of 11:00PM, the i/o stats don't match for the containers. 

![Image](https://github.com/user-attachments/assets/696f3ccc-a3ed-4f9b-ab74-453e8920e22a)
*Shows received network traffic above

![Image](https://github.com/user-attachments/assets/445b0b37-80dd-4ba6-9361-05b8d305cdd7)

### OS / Architecture

Ubuntu

### Beszel version

0.11.0

### Installation method

Docker

### Configuration

```yaml
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    networks:
      - proxy
    extra_hosts:
      - host.docker.internal:host-gateway
    #ports:
    #  - 8055:8090
    #environment:
    #  - USER_CREATION=true
    volumes:
      - ./beszel_data:/beszel_data
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      # Do not remove quotes around the key
      KEY: ssh-******
networks:
  proxy:
    external: true
```

### Hub Logs

```json

```

### Agent Logs

```shell

```

**Comment by henrygd** [comment]
Interesting, thanks for letting me know.

Can you tell me what the `NET I/O` column says for `beszel-agent` when you run `docker stats --no-stream`?

Looks like Grafana (via cadvisor I'm assuming?) says `beszel-agent` is using a constant 4 MB/s. I can't imagine any situation where that would be accurate unless this is somehow related to #457.

**Comment by truncsphere** [comment]
Yes, Grafana via cadvisor. The high usage according docker lasted for about 1h30m, though I'm not sure why. I checked back a week and see no other spikes in regards to Beszel in Grafana. 
The only other container with significant network i/o at the time was my Swag reverse proxy. Grafana and Beszel match in that case. 

I did see the above mentioned issue, but I don't use that for my containers. 



![Image](https://github.com/user-attachments/assets/f793c8e6-7d10-4449-8673-87377b736abd)

**Comment by henrygd** [comment]
It could be that containers using host network mode don't have their traffic tracked in isolation.

I'll look into what cadvisor does when I have time, but I highly doubt the 4 MB/s figure is accurate either. Maybe it's including some other host network traffic.

**Comment by truncsphere** [comment]
I got high i/o alarm again for about the same time last night. It shows Beszel with high I/O during this time. The yellow line below is Swag.  According to my firewall the IP is a T-Mobile IP. 

![Image](https://github.com/user-attachments/assets/a3ffc463-bd9a-45dd-a5a4-f0dcae2712cf)

Going to remove Beszel from Swag external access to test. (It's protected by Pocket-ID)

**Comment by svenvg93** [comment]
@truncsphere Are you still seeing the same problem with the latest versions?

**Comment by truncsphere** [comment]
@svenvg93 
I actually recently decided to remove my Grafana stack in favor of only using Beszel. Checked the history in Beszel and I'm not seeing any spikes tied to Beszel traffic.

**Comment by henrygd** [comment]
That's awesome @truncsphere, I'm glad it's working well for you. I'll close the issue, but let me know if you see this happen again.

**Comment by ramazansancar** [comment]
I am having a similar problem. How can I get a solution?

Problems:
- [ ] Cannot read health statuses correctly. (Can read some containers.)
- [ ] Cannot see CPU, Memory, Disk, and Network usage.


I used the `ghcr.io/tecnativa/docker-socket-proxy:latest` docker image to read the `/var/run/docker.sock:/var/run/docker.sock:ro` data for use in other projects.

Docker Proxy
```
dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
```

Docker Compose file:
```yml
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: [REDACTED]
      KEY: 'ssh- [REDACTED]'
      TOKEN: [REDACTED]
      HUB_URL: http://[REDACTED]:8090

```

<img width="667" height="613" alt="Image" src="https://github.com/user-attachments/assets/befef807-fee0-42fe-9e4e-40a11de47e18" />

<img width="645" height="589" alt="Image" src="https://github.com/user-attachments/assets/2e9769fe-3d36-4324-94a3-25f01658f278" />

<img width="1320" height="770" alt="Image" src="https://github.com/user-attachments/assets/606c9def-7ee0-4de9-a01d-8f651d19a14e" />

<img width="1600" height="884" alt="Image" src="https://github.com/user-attachments/assets/f6edc29d-6708-4562-b1d3-a0f2c393e89d" />

<img width="1592" height="873" alt="Image" src="https://github.com/user-attachments/assets/6c21dc26-8ac5-4857-a93d-ec1efbc8e983" />
