### ISSUE TITLE
[Bug]: When agent goes offline data gets swapped to locally running agent

### ISSUE THREAD

**Issue by ultimaterex** [henrygd/beszel#803]
### Description

I've got a few agents on my hub and I've noticed that when one of the agents goes down it resolves the hostname to the locally running beszel agent. Whenever the agent comes back online it doesn't update to monitor the correct agent unless I restart the hub.

Before:
![Image](https://github.com/user-attachments/assets/7cb4cc5a-b595-42a2-8a8f-39fd0753075e)

After shutting down the agent machine:
![Image](https://github.com/user-attachments/assets/240251fe-01c9-4704-9ef3-70d2b4439a58)

### Expected Behavior

I expect the device to go offline and not swap to the host.docker.internal agent.

### Steps to Reproduce

1. Turn off machine/agent on monitored device 
2. Beszel will swap over to the local hub agent and won't reconnect to the old agent unless hub is restarted

### OS / Architecture

linux/amd64 (agent), linux/arm64 (hub)

### Beszel version

0.11.0

### Installation method

Docker

### Configuration

```yaml
hub + hub-agent:

  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_data:/beszel_data
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8090:8090
    environment:
      - csp="frame-ancestors 'self' http://<hostname>:8080/"


  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      # Do not remove quotes around the key
      KEY: '<redacted>'
```

**Comment by henrygd** [comment]
What happens when you run `ping vortex.lan` from the hub's host machine when the agent is up and the agent is down? Do you see different behavior and/or IP addresses?

Also try `telnet vortex.lan 45876` in both circumstances and let me know what that says, thanks.

**Comment by ultimaterex** [comment]
Pings:

When vortex.lan is available
```sh
rex@sw58x1:~ $ ping vortex.lan
PING vortex.lan (192.168.254.249) 56(84) bytes of data.
64 bytes from vortex.lan (192.168.254.249): icmp_seq=1 ttl=63 time=3.78 ms
64 bytes from vortex.lan (192.168.254.249): icmp_seq=2 ttl=63 time=3.19 ms
...

rex@sw58x1:~ $ telnet vortex.lan 45876
Trying 192.168.254.249...
Connected to vortex.lan.
Escape character is '^]'.
SSH-2.0-Go
```

When vortex.lan is shut down /paused
```sh
rex@sw58x1:~ $ ping vortex.lan
PING vortex.lan (192.168.254.249) 56(84) bytes of data.
From 192.168.11.1 (192.168.11.1) icmp_seq=16 Destination Host Unreachable
From 192.168.11.1 (192.168.11.1) icmp_seq=17 Destination Host Unreachable
...

rex@sw58x1:~ $ telnet vortex.lan 45876
Trying 192.168.254.249...
Connection failed: No route to host
Trying ::...
Connected to vortex.lan.
Escape character is '^]'.
SSH-2.0-Go
```
Telnet seems to hang on trying for about a minute then manages to connect to the host even though it's unavailable.

Once I resume the host in proxmox both ping and telnet immediately return the initial state

**Comment by henrygd** [comment]
Sorry for the delay. Maybe it's caused by having one or both of the `network_mode: host` and `extra_hosts` rules on the hub.

Please try removing those rules and connecting with a unix socket instead. Here's your original config with these changes. Just make sure to edit the localhost system in beszel and change the host to be `/beszel_socket/beszel.sock`

```yaml
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    ports:
      - 8090:8090
    environment:
      - csp="frame-ancestors 'self' http://<hostname>:8080/"

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: '<redacted>'
```
