### ISSUE TITLE
[Bug]: Unable to connect to IPv6 only agent

### ISSUE THREAD

**Issue by tonyliucloud** [henrygd/beszel#810]
### Description

I deployed the hub on a dual stack environment, been able to telnet the agent ipv6:port address and received the correct respond, but shows down on hub.

### Expected Behavior

Should be showing up in hub as hub is deployed on a dual stack VPS.

### Steps to Reproduce

1. Follow https://beszel.dev/guide/hub-installation
2. Add a agent

### OS / Architecture

Debian GNU/Linux

### Beszel version

0.11.1

### Installation method

Binary

### Configuration

```yaml
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # Do not remove quotes around the key
      KEY: 'UPDATE WITH YOUR PUBLIC KEY (copy from "Add system" dialog)'
```

### Hub Logs

```json
{
  "id": "8ct37d09n5apa3e",
  "created": "2025-05-11 22:09:46.624Z",
  "data": {
    "err": "dial tcp [xxxx:xxx:xxx:xxx::a]:45876: connect: network is unreachable",
    "system": "ipv6 test"
  },
  "message": "System down",
  "level": 8
}
```

### Agent Logs

```shell

```
