### ISSUE TITLE
[Bug]: PB API empty

### ISSUE THREAD

**Issue by schulzerik** [henrygd/beszel#824]
### Description

I have a system set up in beszel web interface, which i also have a homepage widget for:

![Image](https://github.com/user-attachments/assets/14672a01-856d-4132-b92e-2789299d62dd)

![Image](https://github.com/user-attachments/assets/3b261b6c-ade6-45a9-b4c4-3ebf7c6bbc4c)

The widget suddenly broke today, the error message lead me to queue the API of PB (/api/collections/systems/records) directly, which is suddenly returning no entrys, even though they exist in PB:

![Image](https://github.com/user-attachments/assets/1f3ed67d-21ff-4144-bafa-92e2aca91331)

![Image](https://github.com/user-attachments/assets/dfcb0eef-4aec-4691-88c0-aef0cefcd528)

### Expected Behavior

System showing up in the API -> Homepage widget working.

### Steps to Reproduce

The error suddenly appeared today. I made a fresh install as an last attempt to troubleshoot, but the error persisted, so:

1. Create empty persistent volume
2. Create docker container for hub and agent
3. Add agent in hub
4. Check PB for agent in systems
5. Queue the API /api/collections/systems/records

### OS / Architecture

Synology DSM (Linux/64)

### Beszel version

0.11.1

### Installation method

Docker

### Configuration

```yaml
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    networks:
      - Reverse-Proxy
    restart: unless-stopped
    volumes:
      - /volume1/docker/beszel:/beszel_data

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    ports:
      - 45876:45876
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /volume1/docker:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMtKIYII+syAAG1EqTZFbOYWRFtAt2bvU7AzAPubRFrY"

networks:
  Reverse-Proxy:
    external: true
```

### Hub Logs

```json
{
  "id": "er7bxwtpjfno00e",
  "created": "2025-05-20 17:41:21.789Z",
  "data": {
    "auth": "",
    "execTime": 0.82511,
    "method": "GET",
    "referer": "",
    "remoteIP": "192.168.100.3",
    "status": 200,
    "type": "request",
    "url": "/api/collections/systems/records",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edg/136.0.0.0",
    "userIP": "192.168.100.3"
  },
  "message": "GET /api/collections/systems/records",
  "level": 0
}
```

### Agent Logs

```shell

```
