### ISSUE TITLE
[Bug]: Volume mount missing from example

### ISSUE THREAD

**Issue by jonashaag** [henrygd/beszel#848]
### Description

I could not get it to work with a single-server setup via the Unix socket method.

I think it's missing this:

```yaml
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
      - ./beszel_socket:/beszel_socket  # <=============== THIS WAS MISSING
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: "ssh-ed25519 ..."
```

In any case I found the tutorial confusing for this single-server use case. Maybe a separate page with instructions would be easier. I was also confused about having to restart the docker-compose setup with the new agent configuration _while being on the UI_? Not sure if that's how it's supposed to be done?

### Expected Behavior

...

### Steps to Reproduce

...

### OS / Architecture

linux amd64

### Beszel version

latest

### Installation method

Docker

### Configuration

```yaml

```

### Hub Logs

```json

```

### Agent Logs

```shell

```
