### ISSUE TITLE
No data when accessing via hostname

### ISSUE THREAD

**Issue by svenvg93** [henrygd/beszel#86]
Not sure this is a bug or something I missed 😅. 
I changed my docker-compose to use the bridge network, instead of the default created one. I can login without a problem with the user account I created before. 
Unfortunately there are no systems shown anymore when I access it via http://hostname:8090. As well as there is no Public key when trying to add a system. 

<img width="1275" alt="image" src="https://github.com/user-attachments/assets/98d94c64-d7e4-4bf7-8857-bfb28459ce34">

When I access it via http://ipaddress:8090, it shows the previously added system and there is a Public Key again. 

<img width="1452" alt="image" src="https://github.com/user-attachments/assets/25b3b5da-58c9-49cf-9b29-c107ca54cec7">

docker-compose.yml;
```
services:
  beszel-hub:
    image: henrygd/beszel:0.1.1
    container_name: beszel-hub
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
    network_mode: bridge
    ports:
      - 8090:8090
    volumes:
      - beszel:/beszel_data

  beszel-agent:
    image: henrygd/beszel-agent:0.1.1
    container_name: beszel-agent
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam 
      PORT: 45876
      KEY: ${KEY}
      FILESYSTEM: /dev/nvme0n1 # set to the correct filesystem for disk I/O stats
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
    beszel:
      name: beszel
```

The `KEY` is present in a `.env` file. Did I miss something when changing to `network_mode: bridge` for the Hub.
