### ISSUE TITLE
[Bug]: cannot connect to agent even from localhost when using Glinet openwrt router. Issue was MPTCP.

### ISSUE THREAD

**Issue by dwyeraidan** [henrygd/beszel#882]
### Description

Just thought I'd write up a note to anyone troubleshooting why they can't connect to the beszel agent.

In my case I have a Glinet Brume 2 router, which runs Openwrt.

After deploying the beszel docker container I couldn't for the life of me connect to the agent no matter where from, or after adding firewall rules.  I have about 20 other hosts, so I'm not new to beszel.
Telnet localhost 45876 was returning nothing.
Other docker guests are accessible over their ports! Just beszel agent that wasn't.
I tried docker agent, as well as the local binary agent.  Wasn't working.

I tested using port 22 for beszel, instead of 45876, which worked! but any other port wasn't. 

After pulling hair out, reviewing syslog, whenever the beszel container was running, there was a kernel error message about MPTCP (multipath tcp).  Glinet must compile their image with mptcp included and this conflicts with Beszel.

So I disabled MPTCP and can now use Beszel agent on my router.

I haven't seen an issue after disabling mptcp but YMMV.

To disable:

```
echo "net.mptcp.enabled=0" > /etc/sysctl.conf
sysctl -p
```

### Expected Behavior

Beszel is accesible, even from localhost.

### Steps to Reproduce

Have mptcp enabled on glinet or openwrt router - run docker container, attempt to telnet localhost 45876.

### OS / Architecture

OpenWrt 21.02, mediatek/mt7981

### Beszel version

0.11.1

### Installation method

Docker

### Configuration

```yaml
services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: "redacted"

```

### Hub Logs

```json
{
  "id": "gwne5ggbt586qsj",
  "created": "2025-06-13 00:39:56.996Z",
  "data": {
    "err": "dial tcp x.x.x.x:45876: i/o timeout", #ip redacted
    "system": "brume"
  },
  "message": "System down",
  "level": 8
```

### Agent Logs

```shell
2025/06/13 04:40:32 INFO Detected root device name=sda1
2025/06/13 04:40:32 INFO Detected network interface name=eth0 sent=6327294505 recv=2336520837
2025/06/13 04:40:32 INFO Detected network interface name=eth1 sent=228345076 recv=768489573
2025/06/13 04:40:32 INFO Detected network interface name=ovpnclient sent=132269422 recv=314709819
2025/06/13 04:40:32 INFO Detected network interface name=tailscale0 sent=2438528 recv=143848006
2025/06/13 04:40:32 INFO Docker 20.10.17 is outdated. Upgrade if possible. See https://github.com/henrygd/beszel/issues/58
2025/06/13 04:40:32 INFO Starting SSH server addr=:45876 network=tcp

```

### Syslog on host

```shell
Fri Jun 13 14:35:00 2025 kern.err kernel: [ 6929.028952] MPTCP: mptcp need to implement this function: net/mptcp/subflow.c,subflow_v4_init_req,1791

```

**Comment by henrygd** [comment]
Thanks for taking the time to share this! I'm not very familiar with Multipath TCP but I'll look further into it.

From a quick search this seems to be a common issue with Go, but you may be able to force enable or disable MPTCP on a per-application basis by setting the env var `GODEBUG=multipathtcp=1` or `GODEBUG=multipathtcp=0`  - https://www.mptcp.dev/setup.html

**Comment by networkoctopus** [comment]
@henrygd thanks so much for the reply.

I can confirm adding `GODEBUG=multipathtcp=0` to my environment variables fixed this for me. As per below snippet.

I have since removed the line "net.mptcp.enabled=0" added to /etc/sysctl.conf (to revert global disabling of MPTCP).

I take it this is an issue with Go, and not Beszel? Please close if so.

Cheers and thanks again for a great app Henry.

```
services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: "ssh-ed25519 redacted"
      GODEBUG: multipathtcp=0
```
