### ISSUE TITLE
[Bug]:  Login Loop Issue on RK3568 (arm64) - beszel_hub Redirects Back to Login Page

### ISSUE THREAD

**Issue by waterver** [henrygd/beszel#916]
### Description

When running beszel_hub on RK3568 (arm64 architecture), the login page continuously redirects back to itself after submitting credentials. This occurs across all deployment methods:

- Docker containers (arm64 image:latest)
- Pre-built GitHub releases
- Locally compiled binaries

Environment: 
- Device: RK3568
- Architecture: aarch64 (arm64)
- OS: Ubuntu 22.04
- Kernel:  5.10.160-geec50f7b347d-dirty 

### Expected Behavior

it can login into the pannel, but rediect to login page rapidly

I use network trace to compare with AMD64 platform（Administrator registration has been performed）, it always redirect by /api/beszel/first-run

I'm not sure this is ARM architecture-related or device-specific. I hope you can check it, and give me suggestions.

### Steps to Reproduce

refer this page: https://beszel.dev/zh/guide/hub-installation

**Docker-compose.yml**
```
services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
```
    
**Install**
`sudo docker compose up -d`

For the binary compiled and github release package, using` ./beszel_linux_arm64 serve --http "0.0.0.0:8090" ` to run the server for test.

After registering my user count, jump to login page, it seems no problem.
However, when I entering information, click login, it return to the login screen a moment after jumping to the pannel(I don't see it finishing loading)

### OS / Architecture

linux/arm64

### Beszel version

0.11.1

### Installation method

Other (please describe above)

### Configuration

```yaml

```

### Hub Logs

```json

```

### Agent Logs

```shell

```
